### ISSUE TITLE
Rework mist bundle

### ISSUE THREAD

**Issue by vanstee** [operable/cog#1051]
The mist bundle was built a while ago and needs some improvement before it's really usable as a modern Cog bundle. To keep consistent with `ecs` and `cfn` bundles, let's rewrite it and break it down into smaller bundles in Ruby using cog-rb. Here's what the final bundles should look like:

# EC2 Bundle

* `ec2:instance-create`
* `ec2:instance-destroy`
* `ec2:instance-list`
* `ec2:instance-search`
* `ec2:instance-reboot`
* `ec2:instance-start`
* `ec2:instance-stop`
* `ec2:instance-tag`
* `ec2:keypairs-list`
* `ec2:vpc-list`

# S3 Bundle

* `s3:bucket-acl`
* `s3:bucket-list`
* `s3:bucket-create`
* `s3:bucket-info`
* `s3:bucket-destroy`
* `s3:file-list`
* `s3:file-create`
* `s3:file-info`
* `s3:file-destroy`

We'll also need to revise the permissions to match this split. I'll post more details as I figure out what works best here.

Along with these bundles, we should spend some time identifying common workflows, like finding instances based on a tag, and rebooting all those instances, which can be explained in detail in the README and in the docs, so users will see how powerful these command pipelines can really be.

Also I'm sure we'll have new commands and use cases popup while working on this. I'll keep this up to date with new commands that get included.

**Comment by kevsmith** [comment]
Closing out since we've released the new `ec2` and `s3` bundles.
