### ISSUE TITLE
UTF-8 characters are not handled properly

### ISSUE THREAD

**Issue by agis-** [operable/cog#1125]
We're on 0.16 and it seems that the parser doesn't handle utf8 properly:

<img width="289" alt="screen shot 2016-11-04 at 12 59 47" src="https://cloud.githubusercontent.com/assets/827224/20003352/a04d5620-a28e-11e6-878f-7b2661562672.png">

**Comment by kevsmith** [comment]
Whoops. I didn't see this issue when I opened #1133
