### ISSUE TITLE
Make global error template user customizable

### ISSUE THREAD

**Issue by kevsmith** [operable/cog#1142]
## Overview
We've gotten several requests to make the error template user customizable. Emerging community consensus is the default error template is great for developers but contains too much information for non-technical users.

## Requirements

1. Cog admins must be able to revert back to the default template at any time.
1. Template customizations must persist across Cog restarts.
1. Documentation of the customization process, including a list of available variables, must be part of the doneness criteria.

## Constraints

1. A global customized error template is good enough for now.

**Comment by mpeck** [comment]
# Proposal

I think we can solve the problem by providing a config option that specifies a path to the error template on the machine running Cog. During startup we check for the config option and replace the standard error template in the db if it is set. Vice versa if it isn't set we just set the error template to the standard one.

This shouldn't require too many changes. We just add the new config option and modify `Cog.Repository.Bundles.maybe_upgrade_embedded_bundle!/1`. It shouldn't require any changes to Cog's template rendering logic. The downside of course is that a changing the template would require a Cog restart and the ability to get the template file onto the machine running Cog. Though to be honest that doesn't seem like a terrible trade off to me.
