### ISSUE TITLE
Use `Plug.RequestId` instead of rolling our own

### ISSUE THREAD

**Issue by christophermaier** [operable/cog#1160]
[Plug.RequestId](https://github.com/elixir-lang/plug/blob/master/lib/plug/request_id.ex) is a thing that exists!

Currently, we generate our own request ID (https://github.com/operable/cog/blob/86e70151d03efa1c12cfc74a9bbfaf03447bbafe/web/plugs/event.ex). We could simplify some of our code by using the standard plug instead.

We'd need to document that the ID format would be different. Additionally, as the plug adds the request ID to the Logger metadata, we'd now get the request ID in our log output (currently, it's just in our audit log).

**Comment by vanstee** [comment]
Just wanted a sanity check before I started on this. In the comments of the `Plug.Event` we mention this:

> Second, it adds a unique request ID. This is distinct from the one
> added by `Plug.RequestId`; we chose not to use that plug and instead
> rolled our own in order to ensure that all correlation IDs used
> across all our events (not just those from the API) had the same
> structure.

Are we no longer concerned about using IDs across all events?

If we do switch to `Plug.RequestId` do we want to keep this `Plug.Event` around for the timestamp metadata it provides?

**Comment by christophermaier** [comment]
@vanstee Derp... forgot about that when I wrote this ticket, sorry. Gonna close this out.
