### ISSUE TITLE
Parsing fails with unicode chars followed by a URL

### ISSUE THREAD

**Issue by agis-** [operable/cog#1161]
The following example demonstrates (ignore the messages from slackbot):

![image](https://cloud.githubusercontent.com/assets/827224/20382083/fc507de8-acb2-11e6-8d08-f1421a3dcab8.png)

While Cog executed the first command, it didn't execute the second.

Happens on 0.16.1 _and_ in the Cog running in http://cogbot.slack.com.

**Comment by kevsmith** [comment]
Preliminary debugging confirms Cog's parser isn't mangling multi-byte Unicode characters. The failure must be happening further along pipeline processing.

**Comment by vanstee** [comment]
Confirmed on master that `echo "ϻ https://google.com"` crashes with the following error:

```
2016-12-06T15:33:53.583 module=Cog.Chat.Slack.Connector line=3 [error] no case clause matching: nil
2016-12-06T15:33:53.585 module=Cog.Chat.Slack.Connector line=3 [error]     (cog) lib/cog/chat/slack/formatter.ex:51: anonymous fn/1 in Cog.Chat.Slack.Formatter.unescape_links/1
    (cog) lib/cog/chat/slack/formatter.ex:66: Cog.Chat.Slack.Formatter.replace/3
    (cog) lib/cog/chat/slack/connector.ex:282: Cog.Chat.Slack.Connector.annotate_message/2
    (cog) lib/cog/chat/slack/connector.ex:39: Cog.Chat.Slack.Connector.handle_message/2
    (cog) lib/cog/chat/slack/connector.ex:3: Cog.Chat.Slack.Connector.websocket_handle/3
    src/websocket_client.erl:384: :websocket_client.retrieve_frame/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by agis-** [comment]
❤️
