### ISSUE TITLE
Include note about COG_HOST in install docs

### ISSUE THREAD

**Issue by vanstee** [operable/cog#1162]
We need a callout about COG_HOST in the new cog-book install docs, just like we had in the old docs.

<img width="771" alt="screen shot 2016-11-17 at 2 54 05 pm" src="https://cloud.githubusercontent.com/assets/228734/20405116/cd6c1a6e-acd5-11e6-8909-982845fcc404.png">

**Comment by Shelton** [comment]
Moving this issue to cog-book repo.
