### ISSUE TITLE
Render tables as preformatted ASCII in HipChat like we do in Slack

### ISSUE THREAD

**Issue by imbriaco** [operable/cog#1186]
We initially implemented table support in HipChat using the native `<table>` tag and friends. Unfortunately, HipChat gives us almost no ability to control the styling of those tables which makes them very difficult to use. For example, we can't even cause it to render table or cell borders, so everything runs together.

![bad](https://cloud.githubusercontent.com/assets/1198/20689684/aec24c6a-b594-11e6-8942-6c4f938dc85d.png)

To work around this we should render tables down to text and return a `<pre>` formatted block like we do in Slack.

I did the initial implementation of this in this branch:
https://github.com/operable/cog/tree/imbriaco/hipchat-text-tables

Here's what it looks like:

![better](https://cloud.githubusercontent.com/assets/1198/20689697/b8c1a710-b594-11e6-919f-d78e2f25edf2.png)

There are a bunch of broken test assertions  in `test/cog/chat/hipchat/templates/embedded/*` that need to be converted from `<table>` to text. It should take an hour or two to work through these. If either @mpeck or @vanstee would be willing to pick this up and carry it over the finish line I'd appreciate it.

cc: @kevsmith

**Comment by imbriaco** [comment]
I should be clear that "implementation" largely means "copy pasta from the slack template processor and adjust as needed". ;)

**Comment by mpeck** [comment]
@imbriaco I can pick it up from here.
