### ISSUE TITLE
Refactor role/group internals

### ISSUE THREAD

**Issue by mpeck** [operable/cog#1191]
The original role/group bits were built when we had a different idea of how roles would work. One part being that roles could not only be assigned to groups but also specific users. We've moved passed a lot of that for different reasons, but a lot of the legacy code still exists in various states of operation. Additionally the code for role management is a bit spread out. There are some pieces that live in controllers and others that live in various repositories. We should consolidate everything to the proper repository.

**Comment by kevsmith** [comment]
Adding to 0.18 so we can discuss & decide if now is a good time to take this on.

**Comment by mpeck** [comment]
For this work I'm thinking that we should probably take a top down approach. Rework the user facing bits first and then refactor the underlying repository.

 - [ ] Update group views
 The simplification of the api should allow us to flatten out the group json.
 Current structure:
  ```
  {
    "group": {
      "id": <id>,
      "name": <name>,
      "members": {
        "groups": [],
        "roles": [],
        "users": []
      }
    }
  }
  ```
  Proposed structure:
  ```
  {
    "group": {
      "id": <id>,
      "name": <name>,
      "roles": [],
      "users": []
    }
  }
  ```

 - [ ] Update dependent apps
   - [ ] cogctl
   - [ ] flywheel

 - [ ] Update create/update interface re: adding users and roles
Because of the complexity of the original group interface we required a separate controller for adding and removing them from groups. We should be able to drop the extra controller and role that up into the update function in the group controller. Most of the code is duplicated anyway. 

I think we can also drop the role_membership endpoint and use the group controller. That would be a bit more consistent, we don't add users to groups via the users endpoint. And, the code in role membership controller is basically just a duplication of the code in the group controller. That could also potentially cut down on api requests. Since users can add both users and roles to a group in one request.

 - [ ] Update dependent apps
   - [ ] cogctl
   - [ ] flywheel

 - [ ] Refactor the group repository (More details to follow once the interface has been confirmed)

**Comment by kevsmith** [comment]
I'm 👍 on reducing the amount of code we have to maintain.

Would leaving the JSON format alone, i.e. keeping the `members` key, while still refactoring the controllers reduce the effort?

**Comment by mpeck** [comment]
Maybe a bit. We may not have to touch quite as much in some of the dependent apps. But imo it wouldn't be a considerable savings, and if we did want to eventually remove it, which I think we should, it seems best to do that before 1.0.

**Comment by kevsmith** [comment]
I agree, in theory at least, that we'd want to change the JSON before 1.0 ships for consistency's sake. However, if we make the change in this case but don't also ripple the same representative change into other data types the values returned from the API are less consistent.

I think the right course of action is (probably) to split changing the JSON representation off into a separate ticket and addressing the change across the whole API at once (at some point in the future).

**Comment by mpeck** [comment]
:+1: I think we are on the same page here.
