### ISSUE TITLE
Review & update all embedded and common templates

### ISSUE THREAD

**Issue by kevsmith** [operable/cog#1219]
Now that Greenbar's behavior has largely stabilized we need to review and revise all of Cog's embedded templates for the following:

1. Does the template render as expected?
1. How does template output look? Is the spacing off? Too many or too few blank lines? 
1. Can the presentation be improved?

Ideally at least two people take on this task to increase velocity and template consistency.

**Comment by vanstee** [comment]
This has already been done as part of the subcommand rework and list template refactorings. Blank lines were also removed as part of the recent greenbar parser changes.
