### ISSUE TITLE
Documentation field should be an array of strings

### ISSUE THREAD

**Issue by kevsmith** [operable/cog#122]
Currently `config.json` allows a single string for command documentation. This significantly complicates writing complete command documentation as the line very quickly runs off the right margin. The less-than-great editing experience encourages terse documentation to avoid line wrapping which is, I think, exactly the opposite outcome we want.

To address this problem I think command documentation should become an array of strings which are joined with `\n` prior to insertion in Cog's database.

Before (taken from [mist](http://github.com/operable/mist)'s `config.json`)

```json
 {
      "name": "ec2-create",
      "version": "0.1",
      "executable": "commands/ec2_create.py",
      "enforcing": true,
      "calling_convention": "bound",
      "env_vars": {
        "AWS_ACCESS_KEY_ID": "",
        "AWS_SECRET_ACCESS_KEY": "",
        "PYTHONPATH": "$INSTALL_PATH"
      },
      "documentation": "mist:ec2-create --region=<region> --type=<type> --ami=<ami> --keypair=<pair> --security-group=<group> --vpc=<vpc> --tags=<tags>"
```

After:

```json
 {
      "name": "ec2-create",
      "version": "0.1",
      "executable": "commands/ec2_create.py",
      "enforcing": true,
      "calling_convention": "bound",
      "env_vars": {
        "AWS_ACCESS_KEY_ID": "",
        "AWS_SECRET_ACCESS_KEY": "",
        "PYTHONPATH": "$INSTALL_PATH"
      },
      "documentation": [
        "mist:ec2-create --region=<region> --type=<type> --ami=<ami> --keypair=<pair>",
        "Optional: --security-group<group_id> --vpc=<vpc_id> --tags=<tags>",
        "Tag format: tag_name1=tag_value,tag_name2=tag_value"
      ]
```

**Comment by vanstee** [comment]
This is no longer needed with the new `long_documentation` option and others.
