### ISSUE TITLE
Remove user-facing mentions of bundle type

### ISSUE THREAD

**Issue by kevsmith** [operable/cog#123]
This will simplify our design and conceptual model, especially for newcomers which lack historical context of previous designs.

**Comment by mpeck** [comment]
@kevsmith is this as simple as removing the bundle type validation check from spanner and then updating the docs? Or am I missing something?

**Comment by lhaskins** [comment]
Initially, since we currently have command bundles that are already using the bundle "type", we will verify that *if* this option is in the config.json file, it should be set to "elixir" or "foreign". If bundle type is not present, the type will default to "foreign".

**Comment by lhaskins** [comment]
https://github.com/operable/spanner/pull/42
