### ISSUE TITLE
Ensure any new v5 bundle configuration features are in place for 1.0

### ISSUE THREAD

**Issue by christophermaier** [operable/cog#1249]
With the removal of support for Mustache templates (see #1248), we'll be removing support for v3 bundle configurations (the last one to support Mustache templates). 

In keeping with our "support back to $CURRENT_VERSION -1" for bundle configuration formats, this means it's a good time to add / change any features in the format for the impending release of Cog 1.0.

**Comment by vanstee** [comment]
Removed support for `subcommands` documentation in v5.
