### ISSUE TITLE
Ensure that permissions mentioned in a rule are in an appropriate namespace

### ISSUE THREAD

**Issue by christophermaier** [operable/cog#125]
Commands should only be managed by permissions from their own bundle, or user-created permissions from the `site` namespace.

When rules are ingested, we should verify that the namespaces for all permissions mentioned are either equal to the mentioned command's bundle, or are `site`.

Bonus points for tooling that can detect this ahead-of-time for bundle authors (in that use case, there should be no `site` permissions mentioned at all, though), but that could come later as an additional enhancement.

**Comment by vanstee** [comment]
This was done as part of the `RuleIngestion` -> `Repository.Rules` work.
