### ISSUE TITLE
Create operable:test-permissions command

### ISSUE THREAD

**Issue by vanstee** [operable/cog#126]
When modifying rules, permissions, roles and groups, it's important to be able to test whether or not you've configured everything correctly, especially with complex hierarchies of groups and roles.

The `operable:test-permissions` command should only run the arguments through the permissions evaluation and should not actually run the command itself. Here's an example:

`@vanstee: operable:test-permissions --command "ec2:terminate --instance-id i-0f9ea3 --environment production" --user kevsmith`

Responding with the follow if the test passes:

`OK, kevsmith has permission to run that command`

or this is the test fails:

`ERROR, kevsmith needs the "ec2:terminate" permission to run that command`

**Comment by vanstee** [comment]
@kevsmith Do you think `COG_ALLOW_SELF_REGISTRATION` is an ok solution to this for now, or is this still needed.

**Comment by christophermaier** [comment]
Closing due to age
