### ISSUE TITLE
Explicitly refuse to run unsupported bundles

### ISSUE THREAD

**Issue by christophermaier** [operable/cog#1262]
Currently, Cog has an `n` and `n-1` policy for which bundle versions it will support. That is, if `v5` is the current bundle configuration version, then you can run `v5` and `v4` bundles, but nothing older.

You cannot install older bundles, but there isn't currently anything that prevents the execution of outdated bundles, should they already be installed on a system prior to the Cog upgrade that removed support. This can cause unexpected failures as Cog tries to execute commands that are built with assumptions of an execution environment that may no longer exist.

We should explicitly disallow the execution of such commands. Ideas include automatic disabling upon upgrade (with some kind of notification to the user / operator), refusal to enable outdated bundles, etc.

**Comment by imbriaco** [comment]
Note that we'll also want to be able to call these out in `bundle list` and `help` much the same way we can disabled bundles.

**Comment by mpeck** [comment]
Incompatible bundle versions are implied by querying the `cog_bundle_version` on the `config_file` column so there are no changes required to the db.

Visually we need to call out incompatible bundles in both chat commands and cogctl.

`help`
Bundles that have *NO* compatible versions installed will show in a new section with an "Incompatible Bundles" header.

`bundle versions`
Incompatible versions should be flagged as "incompatible"

`bundle info`
Incompatible versions should be flagged as "incompatible"

`cogctl bundle info`
Incompatible versions should be flagged as "incompatible"

`cogctl bundle versions`
Incompatible versions should be listed under "incompatible versions". There should be a flag `--incompatible` that only lists incompatible versions for the specified bundle.
Note: There currently is no way to list all bundle versions in cogctl. You must always specify the bundle to list versions on. If a sysadmin wanted to view all incompatible versions he or she would need to first get a list of all bundles and then list incompatible versions for each bundle. This isn't ideal. We should probably allow the listing of all bundle versions via `cogctl bundle versions` sans a bundle name, and then provide optional filtering via the `--incompatible` flag.

`cogctl bundle uninstall`
There should be a flag `--incompatible` that uninstalls just incompatible versions.
Note: It would be nice if we could just accept the bundle list on stdin and then do the right thing. An example workflow might be, `cogctl bundle | cogctl bundle uninstall --incompatible` to uninstall all incompatible bundles.
