### ISSUE TITLE
ECS deletes cog-circuit-driver image

### ISSUE THREAD

**Issue by kevsmith** [operable/cog#1267]
At startup Relay ensures the correct version of the `cog-circuit-driver` image is available in the local Docker environment. If the image doesn't exist at all or a different version is found Relay will pull the correct version from its upstream Docker repo. The driver image is mounted into command containers to make the driver binary available. This allows Relay to have a consistent command execution interface.

Unfortunately ECS will delete the driver image while Relay is running. ECS believes the image is unused since no containers ever directly reference the image. Once the driver image is deleted Relay is unable to execute any commands.

One possible workaround would be for Relay to create, but never start, a minimal container based on the driver image. This would, hopefully, prevent ECS from seeing the image as being unused and subsequently deleting it.

**Comment by imbriaco** [comment]
I think we already do create a container that we don't start, so the ECS logic must be doing something different to find unused images.

Relevant:
https://github.com/operable/go-relay/blob/166ea1dc052a4fb8cbfb73ec305882630071f77d/relay/engines/docker.go#L203

**Comment by imbriaco** [comment]
Relevant, the exact error message was for the `cog-circuit-driver` container being missing rather than the image. The image may also have been missing but we don't know from the report in chat whether or not that's the case. 

The error message reported by tecnobrat in public Slack is:
```
Error response from daemon: No such container: cog-circuit-driver
```

**Comment by vanstee** [comment]
Closing as I was unable to repro with Cog 1.0-beta.1 and ECS agent 1.13.1. After reducing the cleanup interval to 10 minutes, running a few commands, and leaving Cog idle overnight, the circuit-driver container and image were left untouched.

If this problem shows up again and we need a solution, switching to a named volume would solve the issue. We currently only use the circuit-driver image and container to create a volume that contains the circuit-driver executable (which is currently tied to the circuit-driver container, and removed along with it). If Relay instead created a named volume, not tied to any specific container and wrote that executable during startup, we could then mount that named volume on containers used to run commands and remove the circuit-driver image and container after creating the named volume. The volume would not be affected by ECS's image and container cleanup processes.
