### ISSUE TITLE
COG silently fails to tweet when using smart quotes

### ISSUE THREAD

**Issue by pcarranza** [operable/cog#1269]
Currently using version 0.16.2 provided with the docker image.

Cog fails silently when I try to tweet a message and have smart quotes enabled in OSX, this gets fixed by disabling the smart quotes, but it's annoying that COG just does not reply to me when these quotes are being used.

I would suggest that COG fails hard when getting an error like this, or even to say something like: the bundle did not returned any message back. To let me know that COG is actually working.

**Comment by vanstee** [comment]
@pcarranza Could you post the exact command that failed to run? Trying out the following seemed to work on 0.16.2:

```
@cog: echo “test”
```

**Comment by vanstee** [comment]
Wasn't able to reproduce this on Cog 0.17. Cog correctly replaces smart quotes with basic ascii quotes (`"`) and emdashes with `--`. @pcarranza feel free to reopen if this is still an issue.

**Comment by pcarranza** [comment]
@vanstee sorry I wasn't around. It failed with tweeting, the command was something like `!tweet "hey there"` but with smart quotes enabled.

Don't know if this makes a difference.
