### ISSUE TITLE
Add --force flag to cogctl delete/remove commands

### ISSUE THREAD

**Issue by vanstee** [operable/cog#1328]
Now that we made many foreign key relationship constraints restrict on delete, we need to add a `--force` flag to cogctl for convenient operation. We'll also need to support these changes in Cog. Here's a list of all commands that need to support this flag:

* `cogctl bundle uninstall`
* `cogctl users delete`
* `cogctl groups delete`
* `cogctl relays delete`
* `cogctl relay-groups delete`
* `cogctl roles delete`
* `cogctl permissions delete`

**Comment by christophermaier** [comment]
This issue was moved to operable/cogctl#133
