### ISSUE TITLE
Cogctl incorrectly displays errors by iterating over characters

### ISSUE THREAD

**Issue by vanstee** [operable/cog#1361]
```
(cogctl) $ bin/cogctl user
Error: I n v a l i d   c r e d e n t i a l s
```

Should read:

```
(cogctl) $ bin/cogctl user
Error: Invalid credentials
```

**Comment by christophermaier** [comment]
This is actually because sometimes we send back a list of strings, and others, just a string.

This may already be solved on master, though: https://github.com/operable/cogctl/blob/00ba834ed4b85cb7765337e343df976011e37927/cogctl/cli/decorators.py#L34

**Comment by kevsmith** [comment]
Seems to be there on latest master:

```
11:36:57 samedi:work/cogctl/(master) $ ~/bin/cogctl -p public2 user
Error: I n v a l i d   c r e d e n t i a l s
```

Investigating...
