### ISSUE TITLE
reduce case sensitivity

### ISSUE THREAD

**Issue by Erreinion** [operable/cog#1373]
When connecting to a chat client with a mobile device, the default behaviour is to capitalise the first character.

Cog returns an "Illegal Character" error for any command starting with a capital character.
`> Help`

```
Command Error
The specific error was:

```illegal characters "H"```
```

But if one puts a capital letter after the first character, Cog returns a "Command not found" error:
` > hElp`
```
Command Error
The specific error was:

```Command 'hElp' not found in any installed bundle.```
```

I'm not sure why the first character is treated differently, but it appears to be a bug. 

And since chat and mobile seem to go together naturally, it would seem appropriate to have more graceful handling of first character capitals.

Is it even possible to create 2 commands with different cases? `help` and `Help`? If not, a lower() on the whole command seems like a good thing to do.

Not sure to label this as a bug or a feature request.

**Comment by nmohoric** [comment]
Taking a bit of a stab in the dark, but I think this may be a bug (feature?) in Piper?
https://github.com/operable/piper/blob/master/src/piper_cmd2_name_lexer.xrl

I may be totally wrong though, still familiarizing myself with the codebase.
