### ISSUE TITLE
The "Cog Book" shows a security warning in Chrome and Firefox

### ISSUE THREAD

**Issue by sjuxax** [operable/cog#1386]
Clicking through to the Cog Book displays an insecure connection warning for me in both Chrome and Firefox. It seems that this URL is forwarding to servers provided by github, and the certificate provided is only valid for github and related domains.

URL affected: https://cog-book.operable.io/index.html (anything under cog-book.operable.io)
Chrome version: Version 57.0.2987.133 (64-bit)
Firefox version: 52.0.2 (32-bit)
Error from Firefox:
```
cog-book.operable.io uses an invalid security certificate. The certificate is only valid for the following names:
www.github.com, *.github.com, github.com, *.github.io, github.io, *.githubusercontent.com, githubusercontent.com

Error code: SSL_ERROR_BAD_CERT_DOMAIN
```

I've been seeing this for at least the last week or so. I'm not sure if this is the right place to report this, but I'm surprised it's been this way for so long, so thought I should let someone know.

**Comment by agis** [comment]
I guess this is until the Operable ppl migrate to LetsEncrypt.
