### ISSUE TITLE
Stateless Relays

### ISSUE THREAD

**Issue by kevsmith** [operable/cog#140]
Placeholder issue to remind @imbriaco and @kevsmith

**Comment by christophermaier** [comment]
Relays should be effectively stateless. Configuration and bundles would be pushed by / pulled from Cog on startup, with management driven from Cog. Additionally, bundles should be able to be downloaded from Cog or "not Cog" (e.g., S3 bucket, Github releases, a future "Cog marketplace", etc.)

**Comment by vanstee** [comment]
@kevsmith Pretty sure this is done now that we have the new go relay

**Comment by vanstee** [comment]
This might still be relevant in some cases, but since we rewrote the entire relay in Go, I think this issue can be closed for now.
