### ISSUE TITLE
Define canonical format for aggregate values

### ISSUE THREAD

**Issue by kevsmith** [operable/cog#141]
While testing [mist](https://github.com/operable/mist)'s EC2 commands I discovered Cog doesn't marshal aggregate values (maps in this instance but I suspect arrays meet the same fate) into the foreign command environment in any kind of useful way.

I discovered this by running the command pipeline:

```shell
ec2-find --region=us-west-2 --return="id,tags,region" | ec2-tag --region=$region --remove --tags=$tags $id
```

This should remove any tags currently assigned to instances in us-west-2. The pipeline reported success (displayed "ok" in Slack) but didn't remove any tags. I suspect the problem is that tags are returned as a map by `ec2-find` and either the foreign command interface mangles them and/or our lack of a defined format for maps and lists renders the receiving foreign command code unable to parse the incoming data.

For reference here's an example invocation and output of `ec2-find`:

```shell
> ec2-find --region=us-west-2 --return="id,tags,state,pubip"
{
  "tags": {
    "environment": "testing"
  },
  "state": "running",
  "region": "us-west-2",
  "pubip": "52.34.132.70",
  "id": "i-2d9934ea"
}
```

**Comment by vanstee** [comment]
Fixed now that all commands are multi and return arrays of json.
