### ISSUE TITLE
Survey the authorization-related commands (and API) for usage style

### ISSUE THREAD

**Issue by christophermaier** [operable/cog#146]
The authorization commands evolved organically, and don't necessarily reflect usage patterns that will actually occur in real life. For instance, the `operable:role` command cannot manipulate which permissions are in the role; to do this, you have to use the `operable:permissions` command, which is a little surprising. 

We should take a comprehensive survey of the following commands to make sure their usage reflects the kinds of flows we want to support, and that they are all mutually consistent:
* operable:rules
* operable:group
* operable:role
* operable:permissions
* operable:bundle

**Comment by vanstee** [comment]
This has been fixed as we've rewritten a lot of these commands to have sane flags and args.
