### ISSUE TITLE
Bundle tooling (we need some)

### ISSUE THREAD

**Issue by kevsmith** [operable/cog#167]
Current state of command packaging tools is not great. We need a common set of cross platform tools command authors can use for packaging and writing commands. The phrase "cross platform" in this context means portable in the sense tool source code can be built on multiple OSs.

Tool ideas:
- Generate `config.json` from a less verbose description
- Generate `manifest.json` and bundle file from a directory structure
- Validate `config.json` (rule syntax, command definitions, well-formed JSON, etc)

Whoever works on this issue should validate design and scope of work with @kevsmith before proceeding.

**Comment by vanstee** [comment]
config.json and manifest.json are no longer required for bundles. We could generate a base bundle, but the config is super minimal now and this is less important.
