### ISSUE TITLE
Verify operable commands have the correct execution and calling_convention

### ISSUE THREAD

**Issue by lhaskins** [operable/cog#175]
We should verify that each of the operable commands have the correct execution and calling_convention set. This will clarify the use of required inputs for each of these commands with the use of pipelines moving forward.

For example, for the `wc` command, should the `execution`=`once` with the `calling_convention`=`all` or are the defaults just fine. 
Currently, in order to execute wc in a pipeline we must execute: 
`> @bot echo "foo" | wc --lines $body[0]`
We should be able to do it as follows:
`> @bot echo "foo" | wc --lines`

**Comment by vanstee** [comment]
This is no longer applicable after removing execution bits.
