### ISSUE TITLE
Sort out websocket_client dependency properly

### ISSUE THREAD

**Issue by christophermaier** [operable/cog#217]
Currently, we depend on `websocket_client` from https://github.com/jeremyong/websocket_client, which is what our [Slack library](https://github.com/BlakeWilliams/Elixir-Slack) uses. However, this is not a Hex package, and thus is excluded from the Slack Hex package we use. There is a `websocket_client` package in Hex, but it is from a fork of a fork of the library we use, and has diverged far enough to not be a drop-in replacement. It has some nice bug fixes that we'd ultimately like to take advantage of, though.

**Comment by vanstee** [comment]
While this is still a good idea, we haven't had any issues with the jeremyong repo so I'm going to close for now. Let's investigate further if we hit any bugs or need to rewrite that code for some reason.
