### ISSUE TITLE
Pager Duty Command Bundle

### ISSUE THREAD

**Issue by kevsmith** [operable/cog#222]
We need a bundle of Cog commands wrapping Pager Duty's API. We're receptive to ideas about how this should look. We're even _more_ receptive to code implementing one or several commands.

Some suggestions to get creative juices flowing:

- List all of the active rotations for a PD account
- Display who is on-call now and next up for a given rotation
- Ack an alert
- Snooze an incident
- Send a page

**Comment by vanstee** [comment]
I think @mpeck already finished this https://github.com/cogcmd/pagerduty/
