### ISSUE TITLE
Improve Cog's AWS chops

### ISSUE THREAD

**Issue by kevsmith** [operable/cog#223]
Cog has a basic set of EC2 and S3 commands available in the [mist](https://github.com/operable/mist) bundle. Mist is written in Python and uses the excellent [boto](http://boto.cloudhackers.com/en/latest/) library. Contributions expanding Mist's repertoire would be awesome.

Some project ideas:

- A command to generate signed S3 URLs
- Commands wrapping the AWS commands you use the most
- Commands to manage CloudFormation deployments
- Commands for managing deployment keys

**Comment by howdoicomputer** [comment]
Heya!

Support for AWS Lambda's would be super swell! I've come to really like using Lamda as a pseudo-Jenkins replacement as far as operations tasks. I certainly wouldn't mind helping but I see that there maaaaaay be a blocking issue for that.

 https://github.com/operable/cog/issues/847

I can help with that one too but I'm not sure where to start and I don't want to step on anyone's toes.

**Comment by vanstee** [comment]
I'll keep this in mind when working on the new s3 and ec2 bundles.
