### ISSUE TITLE
Formalize and stabilize chat adapter API

### ISSUE THREAD

**Issue by imbriaco** [operable/cog#224]
We need to formalize the contract and API between cog and adapters. We currently have the `Cog.Adapter` behavior, but that doesn't express the full interface or provide much guidance about how responsibility is divided between cog and adapters.

As we're doing this, we need to consider both the minimum required API as well ways that we can make additional features that are unique to a chat provider available to cog and commands. We don't need to fully define how additional chat provider specific capabilities are exposed, but we should at least design with an eye toward not cutting off those capabilities in the future.

**Comment by vanstee** [comment]
This was done when we created an adapter behavior.
