### ISSUE TITLE
In a pipeline, the executor fails to handle commands that return empty lists

### ISSUE THREAD

**Issue by christophermaier** [operable/cog#233]
If a command produces an empty list as output, our templating engine can handle that and can be used to print an informative message.

However, if the same command is instead part of a pipeline, we don't handle the passing of that empty list to downstream commands well. For example:

```
!rules --list --for-command=operable:echo | raw
@chris Whoops! An error occurred. No output received from command 'operable:rules --list --for-command=operable:echo'
```

In this particular case, I'd expect `raw` to output something like `[ ]`.

In the general case, though, the following should happen. If the executor receives an empty list:

* It can pass it to a `once/all` command and that command should gracefully handle it
* If the next command is a `multiple`, we can skip it as a no-op (mapping over an empty list is an empty list)
* If the end of a pipeline is reached with an empty list and no template is provided, then we output a message along the lines of "Pipeline completed, but no data was returned"

**Comment by vanstee** [comment]
Waiting to implement this until https://github.com/operable/cog/issues/286 is completed.

**Comment by mpeck** [comment]
@christophermaier this looks like you fixed it in the executor refactor. Can we close this guy?

**Comment by christophermaier** [comment]
@mpeck Yup, this got fixed in the refactor. Closing now.
