### ISSUE TITLE
Filter command should take a "--path" option instead of "--field"

### ISSUE THREAD

**Issue by christophermaier** [operable/cog#256]
We currently do not deal with nested keys yet, so the addition of a `--path` option is needed. This would allow specifying a key path to nested objects with a dot notation, e.g., `--path=foo.bar.baz`, which could be used to target `"hello world"` in the object `{"foo": {"bar": {"baz": "hello world"}}}`, for instance.

It should also handle array indexing as well, e.g. `--path=foo.bar[0]` would target `"hello"` in this object:

```json
{
  "foo": {
      "bar": ["hello", "world"]
  }
}
```

Since dots are legal in JSON field names, we should also allow this by quoting such fields, so `--path=foo."bar.baz".quux` would target "hello" in this object:

```json
  {
      "foo": {
          "bar.baz": {
              "quux": "hello"
          }
      }
  }
```
(This may or may not require some tweaking of Piper, though; that needs investigation)

This would subsume the current `--field` option (a field is just a path of length 1, after all), so we'll need to remove the `--field` option.

Also, `filter` currently accepts a `--matches` option without a corresponding `--field` option. This should be disallowed; `--matches` only makes sense with `--field` (well, with `--path` once this feature is complete)

Just like `--field`, `--path` can continue to be specified alone; in this case, we let the input object through if it has data at the specified path.

Specifying no options (as in, e.g., `something | filter | something-else`) is allowed, but is effectively a no-op)

**Comment by lhaskins** [comment]
Currently, if executing `seed '{"foo":{"bar":{"baz":"stuff"}}}' | operable:filter --path=foo.bar`, piper sets the path option to `foo` and drops the remaining path. So piper will need to be updated to be able to handle the path.
`seed '{"foo":{"bar":{"baz":"stuff"}}}' | operable:filter --path="foo.bar"` returns the path as `foo.bar`

**Comment by christophermaier** [comment]
Just to be clear here, you're saying that the value of the `--path` option would currently need to be enclosed in quotes in order for Piper to capture the entire dot-delimited string, correct?

Any insight as to how Piper currently behaves with internally-quoted fields in a path, e.g. `foo."bar.baz".boo`?

**Comment by lhaskins** [comment]
Yes, in order for the entire path to be sent, it must be enclosed in quotes.
- `foo."bar.baz".boo` returns `foo` as the set path option to the command. 
- `'foo."bar.baz".qux'` returns `"foo.\"bar.baz\".qux"`

Without a change to Piper, the path field can be a bit touchy when it comes to the quotes.

**Comment by kevsmith** [comment]
The string patterns in `Piper.Command.Lexer` on lines 40 and 41 need to be tweaked a bit.

**Comment by lhaskins** [comment]
The issue states that we should not allow filter to only use the `matches` option without using the `path` option. If we restrict the command in this manner, we eliminate the possibility of this sort of behavior:
 ```seed '[{"a": "1", "b": "2"}, {"a": "3"}]' | filter --matches="b" | echo $a``` 
where the result should be `1`. We don't really need a path, we just want to filter out any info that matches.

**Comment by christophermaier** [comment]
@lhaskins This is explicitly desired. Previously if only `--matches` were given, we'd match the regex against the JSON string encoding of the object. This runs into weird situations where you could match either key or value (or even weird combinations of the two). The desired behavior going forward is to require explicit targeting of a `--matches` option using `--path`
