### ISSUE TITLE
Commands expecting a COG_ENV should fail gracefully if at the beginning of a pipeline

### ISSUE THREAD

**Issue by christophermaier** [operable/cog#265]
Commands such as `operable:table`, `operable:filter`, etc. are intended to operate on data produced by other commands in front of them in a pipeline. If they occur at the _front_ of a pipeline, though, they will crash.

Instead, they should handle this gracefully and return an error to the user indicating that they are not intended to begin pipelines.

**Comment by vanstee** [comment]
Commands no longer crash as we provide `[%{}]` as the initial value. They don't really produce meaningful results but I think that'd be expected from a command like `table`.
