### ISSUE TITLE
Improve Bundle configuration ergonomics

### ISSUE THREAD

**Issue by imbriaco** [operable/cog#273]
Currently Bundle configuration uses JSON files to specify a number of details about the bundle and commands contained within it. Things like the rules, permissions, command details (names paths, options, etc) and so on are all defined in this file. Our goal should be to streamline the process of creating and configuring a commands to the maximum extent possible for both simple and complex commands.

There are a some areas that were discussed in the private alpha chat where we may be able to improve our configuration in that direction:

- Optional fields should be optional. Regardless of whether we ultimately change the format of the configuration, we should loosen up our validation rules to allow optional fields or fields that have sane defaults to be missing from the configuration.
- Reconsider JSON. Is this the best way to represent this configuration? JSON has the unfortunate attribute of not allowing comments which can be a real detriment for hand-written or particularly long configurations. YAML, HCL, or some other format might be a better option.
- Others?

cc: @technicalpickles

**Comment by mpeck** [comment]
I think I see a couple issues here. 1) Switching our config to something more friendly and 2) making optional fields optional.

Regarding 1:
Everyone seems to be in agreement that YAML is the way to go. It's common and relatively easy to implement. There are a few libs that we can use. yaml-elixir (https://github.com/KamilLelonek/yaml-elixir) seems like a decent one to start with. It's a wrapper around yamerl (https://github.com/yakaz/yamerl) which is a yaml parser written in erlang.
Questions:
  * Does the manifest.json also need to change to YAML? It seems like the manifest is something that will most often be generated. It's also pretty simple so it's easy for a human to parse if need be.

Regarding 2:
We need to loosen up on validation. If a field is optional, then it should be optional. If we can come up with a sane default for a field, then we should do that.

Both changes will require work in both relay and spanner. Specifically centered around `Relay.Bundle.Installer` and `Spanner.Bundle.ConfigValidationError`.

Tasks
- [ ] Switch config file format to YAML
- [ ] Make optional options optional

**Comment by lhaskins** [comment]
We should also migrate our dynamic configuration files.

**Comment by christophermaier** [comment]
I think that dynamic configuration being moved to YAML can be a separate piece of work. As http://www.yaml.org/spec/1.2/spec.html#id2759572 suggests, the existing JSON files could be parsed as YAML anyway, which would simplify that.

I like the idea of leveraging JSON Schema to validate the configuration maps, even though they come from YAML; that's kinda slick.

Those libraries for YAML parsing and schema validation look nice; minimal dependencies and pure implementations FTW.

:+1:
