### ISSUE TITLE
The cog us-east-1 ami's installed erlang doesn't support dirty CPU schedulers

### ISSUE THREAD

**Issue by anfleene** [operable/cog#292]
Hi!

I attempted to setup cog using the ec2 us-east-1 ami(ami-29c3f043) and when I ran the setup script it failed:
```bash
operable@ip-10-0-131-33:~$ ./setup.sh
Loading environemnt variables from /home/operable/cog.vars.
Erlang installed...../usr/local/bin/erl
Elixir installed...../usr/local/bin/iex
Mix installed...../usr/local/bin/mix
Make installed...../usr/bin/make
Git installed...../usr/bin/git
Erlang dirty CPU schedulers supported.....No
Detected Erlang '/usr/local/bin/erl' lacks required dirty scheduler support.
See http://erlang.org/doc/installation_guide/INSTALL.html for more information.
Setup aborted.
```

I haven't tried any of the other ami's so it could just be the us-east one.

Let me know if you need anything else from me, cog looks awesome.

Thanks,
Andy

**Comment by fromonesrc** [comment]
What instance type are you running? If you're running a single core instance you'll need to set `ERL_OPTS="-smp true"` in your environment.

**Comment by anfleene** [comment]
That was it I was using a t2.small.
I booted a t2.medium and it's working.
Thanks!

**Comment by imbriaco** [comment]
Thanks for the report, I'm going to update the cog.vars file on this AMI to always have that ERL_OPTS value set so this doesn't bite people in the future.
