### ISSUE TITLE
Docker fails to compile hedwig during build

### ISSUE THREAD

**Issue by sgerrand** [operable/cog#300]
Running `docker build .` currently fails when compiling [`hedwig`](https://github.com/hedwig-im/hedwig).

Backtrace:
```
==> hedwig
Compiled lib/hedwig.ex
Compiled lib/hedwig/client/supervisor.ex
Compiled lib/hedwig/config.ex
lib/hedwig/handlers/help.ex:25: warning: you are piping into a function call without parentheses, which may be ambiguous. Please wrap the function you are piping into in parentheses. For example:

    foo 1 |> bar 2 |> baz 3

Should be written as:

    foo(1) |> bar(2) |> baz(3)

Compiled lib/hedwig/registry.ex
Compiled lib/hedwig/helpers.ex
lib/hedwig/jid.ex:50: warning: redefining @doc attribute previously set at line 27
Compiled lib/hedwig/jid.ex
Compiled lib/hedwig/supervisor.ex
Compiled lib/hedwig/transport.ex
Compiled lib/hedwig/xml.ex
Compiled lib/hedwig/xmlns.ex
Compiled lib/hedwig/client.ex
Compiled lib/hedwig/conn/features.ex
Compiled lib/hedwig/handler.ex
Compiled lib/hedwig/conn.ex
Compiled lib/hedwig/auth.ex
Compiled lib/hedwig/transports/tcp.ex
Compiled lib/hedwig/stanzas/iq.ex
Compiled lib/hedwig/stanza/parser.ex
Compiled lib/hedwig/stanzas/message.ex
Compiled lib/hedwig/stanzas/presence.ex
Compiled lib/hedwig/handlers/great_success.ex
Compiled lib/hedwig/handlers/echo.ex
Compiled lib/hedwig/handlers/help.ex
Compiled lib/hedwig/stanza.ex
Compiled lib/hedwig/handlers/panzy.ex
Compilation failed due to warnings while using the --warnings-as-errors option
could not compile dependency :hedwig, "mix compile" failed. You can recompile this dependency with "mix deps.compile hedwig", update it with "mix deps.update hedwig" or clean it with "mix deps.clean hedwig"
The command '/bin/sh -c mix deps.get && mix deps.compile' returned a non-zero code: 1
```

**Comment by sgerrand** [comment]
:memo: The cause of this issue is the upstream `hedwig` package, which appears to be resolved in the 1.0.0 version (which is only a release candidate release). Once that gets publicly released, this problem should be resolved.

**Comment by sgerrand** [comment]
Related to hedwig-im/hedwig#30

**Comment by christophermaier** [comment]
But see also #59... I think upgrading Hedwig will require some additional code changes

**Comment by imbriaco** [comment]
That's very strange. I can duplicate the warning, but it doesn't abort compilation for me. The warnings_as_errors in elixirc_options seems like it's only being used for building Cog itself, and not for dependencies. 

Are you building against master?

Do you have any environment variables set for `ALLOW_WARNINGS`, `ERL_*` or `ELIXIR_*` ?

**Comment by sgerrand** [comment]
@imbriaco: 

> Are you building against master?

Yep.

> Do you have any environment variables set for ALLOW_WARNINGS, ERL_* or ELIXIR_* ?

Nope.

```
env | ag '(ALLOW_|ERL_|ELIXIR_)'
PERL_MB_OPT=--install_base "/Users/s/perl5"
PERL_MM_OPT=INSTALL_BASE=/Users/s/perl5
```

**Comment by sgerrand** [comment]
> I think upgrading Hedwig will require some additional code changes

@christophermaier: Indeed it will. :+1:

**Comment by imbriaco** [comment]
I've tried to duplicate this and I'm still not able to do so. I went so far as to clone a brand new copy and removed all the images from my Docker host to make sure I wasn't using something cached, and I'm still not able to get the compile to fail on a warning in a dependency.

Could you try removing (or at least pulling a new copy of) `operable/docker-base` to make sure there's not something fishy with the base image? I'd be surprised if there's anything that could cause this in there. The other thing that's maybe worth trying is `docker build --no-cache .` to make sure there' not something strange cached.

**Comment by sgerrand** [comment]
> Could you try removing (or at least pulling a new copy of)
operable/docker-base to make sure there's not something fishy with the base
image? I'd be surprised if there's anything that could cause this in there.
The other thing that's maybe worth trying is docker build --no-cache . to
make sure there' not something strange cached.

Good idea! Apologies, I should have tried that earlier.

**Comment by sgerrand** [comment]
> Could you try removing (or at least pulling a new copy of) `operable/docker-base` to make sure there's not something fishy with the base image? I'd be surprised if there's anything that could cause this in there. The other thing that's maybe worth trying is `docker build --no-cache .` to make sure there' not something strange cached.

I did both and the image built successfully. Thanks! :tada:
