### ISSUE TITLE
Handle pending migrations at launch time

### ISSUE THREAD

**Issue by imbriaco** [operable/cog#301]
When Cog is launched, we should detect pending migrations and do one of two things:

1. By default, we should emit a message that says that a database migration is required, provides the necessary commands to run and a documentation link, and exits.
2. If an environment variable is set (perhaps `COG_APPLY_MIGRATIONS` or the like), automatically apply migrations before starting.

**Comment by vanstee** [comment]
This has been implemented: https://github.com/operable/cog/blob/master/lib/cog.ex#L134-L146
