### ISSUE TITLE
Reconsider chat handles as identity

### ISSUE THREAD

**Issue by imbriaco** [operable/cog#305]
There was a good conversation in cogbot chat tonight (thanks @ptinsley!) regarding handles and the safety of using them as a primary identifier to map chat provider users to cog users. I think there is a big enough concern that we should consider moving from handles to provider-specific user IDs. In cases where there may not be a user ID (ahem, IRC) we will have to be creative and carefully document the tradeoffs we make. 

The primary problem with handles is that they can be changed by users. In the case of HipChat, for example, it's particularly troublesome since two different users can have what appears to us via XMPP to be exactly the same handle as long as they're not in the same room at the same time.

I think we can keep using handles for provisioning users, we just look them up at handle create time and convert to permanent IDs. There's a short but acceptable race condition there.

**Comment by vanstee** [comment]
Closing in favor of https://github.com/operable/cog/issues/353
