### ISSUE TITLE
Prevent users from creating aliases with fully qualified names

### ISSUE THREAD

**Issue by mpeck** [operable/cog#314]
We should prevent users from aliasing fully qualified names as the final alias name will not be what they expect:
![screen shot 2016-02-26 at 2 15 05 pm](https://cloud.githubusercontent.com/assets/13558/13362573/5c15bfd6-dc93-11e5-8e18-6b6e75a5dcb2.png)

**Comment by mpeck** [comment]
Some clarity on this @kevsmith. It looks like we have some issues when creating aliases with colons period. The exception being when they appear as the first character. It seems to resolve mostly around how we identify commands vs aliases with some parser issues sprinkled in.

For example:
```
> alias new :foo "echo foo"
    success
> :foo
    foo (success)
> alias new foo: "echo foo"
   fails
> alias new "foo:" "echo foo"
   success
> foo:
   fails
> alias new :kiss:me "echo kiss me"
   success
> :kiss:me
   kiss me (success)
> alias new dont:shipit: "echo don't shipit"
   success
> dont:shipit:
   fails
> alias new my:alias "echo my alias"
   success
> my:alias
   fails
```

I think we could solve the specific issue pretty easily by just preventing users from having aliases that don't start with a colon from having colons anywhere in the string. Any thoughts?

**Comment by kevsmith** [comment]
It's the same parser issue under the covers I think. There's a lexer rule for the command parser that's not quite right wrt strings and namespaced names. I dug into it some last night but wasn't able to figure out what's going on.

```elixir
# This should fail to parse.
# Note: Using the command name as the bundle name is expected as it's
# the parser's default behavior now.
iex(2)> {:ok, ast} = Piper.Command.Parser.scan_and_parse("foo: bar")
 %Piper.Command.Ast.Invocation{args: [%Piper.Command.Ast.String{col: 4, line: 1,
    value: ":"}, %Piper.Command.Ast.String{col: 6, line: 1, value: "bar"}],
  col: 1, command: "foo:foo", line: 1, options: [], redirs: []}}
iex(3)> "#{ast}"
"foo:foo : bar"
iex(4)>
```

**Comment by mpeck** [comment]
dependent on #340

**Comment by vanstee** [comment]
Since we're ignoring `:ws` tokens (whitespace), anything that retains the right order can be parsed correctly even though it includes whitespace on a token boundary.

For instance after lexing `foo: bar` the parser sees ` [{:string, {1, 1}, 'foo'}, {:colon, {1, 4}, ':'}, {:string, {1, 6}, 'bar'}]` instead of `[{:string, {1, 1}, 'foo'}, {:colon, {1, 4}, ':'}, {:ws, {1, 5}, ' '}, {:string, {1, 6}, 'bar'}]` and just continues parsing the command as if it were originally `foo:bar`. Not ignoring whitespace and failing during parsing seems like a good way to at least fix @kevsmith's example, but we'll have to rewrite most parsing rules to include whitespace tokens.

**Comment by vanstee** [comment]
It also looks like this is the same underlying bug from @mpeck's examples. `colon` tokens cause the two adjacent `string` tokens to be parsed as a `name` token, which is causing the weirdness there and also why things like `alias new "foo:" "echo foo"` are still parsed correctly.

Here's a plan of action:

- [ ] Stop ignoring whitespace tokens
- [ ] Rewrite parsing rules to take into account required whitespace tokens
- [ ] Add an additional check in the alias command to disallow alias names that look like fully qualified command names

**Comment by vanstee** [comment]
@kevsmith Was able to cheat a little bit and also include some nicer error message than including whitespace tokens would have provided. The result is that any string/name token that starts or ends with a colon emits a `bad_token` which causes the parser to emit a nice warning.
