### ISSUE TITLE
Rendering multiple templates with `nil` outputs`

### ISSUE THREAD

**Issue by lhaskins** [operable/cog#316]
When a multiple execution command returns `nil` for all inputs on a list input, the output returned is an empty string regardless of the template used.

For example, currently, the following command:
```seed '[ {"key": "Name", "value": "test1"}, {"key": "Name", "value": "test2"} ]' | operable:filter --path="value" --matches="Name"```
returns:
""
If it were a single element in the list the template would be used to render the overall output:
```seed '[ {"key": "Name", "value": "test1"} ]' | operable:filter --path="value" --matches="Name"```
returns:
```{"result": null}```

**Comment by lhaskins** [comment]
I believe this problem is located in the executor where the template is being rendered when the context is an empty list.

**Comment by vanstee** [comment]
I think this may have already been fixed as we're now returning an empty list for both commands above. 

![screen shot 2016-05-03 at 3 08 46 pm](https://cloud.githubusercontent.com/assets/228734/14995087/04d13bd2-1141-11e6-981c-5b97274897b4.png)

**Comment by vanstee** [comment]
@kevsmith Could you confirm that this is no longer an issue? Just wanted to make sure I wasn't missing something.
