### ISSUE TITLE
Rendering different templates based on command output

### ISSUE THREAD

**Issue by lhaskins** [operable/cog#319]
Now that it is possible to return `nil` as an output for commands, when executing in a pipeline, it is possible to use the wrong template for the command output. We should be using the last template in the pipeline for a non-nil response.

In the situation where a command may want to use an "empty results" template if the results are empty, it is possible to return that response if the last execution returned a nil response regardless of the previous responses.

For example, given the following command execution:
```seed '[{"foo":{"bar.qux":{"baz":"stuff"}}}, {"foo": {"bar":{"baz":"me"}}}]' | operable:filter --path="foo.\"bar.qux\".baz"```
The first item should return output, the second, should return nil. The template from the first should be used to display the output. It currently displays according to the nil response (the last command execution in the pipeline)

**Comment by kevsmith** [comment]
Looks like the executor isn't buffering output before sending it to the user :(

**Comment by vanstee** [comment]
I thought it wasn't possible to return `nil` as output for a command since the executor strips those out. Did that change recently? If not it might just be a bug in the executor that we can fix.

**Comment by lhaskins** [comment]
Yes, it is a bug in the executor. It is possible to return no results from a filter command and we definitely want them stripped out (https://github.com/operable/cog/pull/219), but we need to have the ability to say that no results were found if that is the case.
