### ISSUE TITLE
MFA Support

### ISSUE THREAD

**Issue by kindlyseth** [operable/cog#326]
Cog will run commands for any user authenticated with the chat system in use. This is a problem if you only take sensitive actions from certain machines (say a employer owned laptop,) but need to have your chat client (Slack) on less secure devices such as your phone.

The goal of this issue is to have an out of band way of confirming sensitive actions. It might be as simple as a password protected web page that you can keep open only on a secured device.

**Comment by kindlyseth** [comment]
My employer is interested in this, but I'm on other projects for the next few days.

**Comment by vanstee** [comment]
Great idea. I know @imbriaco and @kevsmith have been throwing this idea around for a while, so I'm sure they'll have some details to add.

Confirmable commands, commands which require another user to sign-off on, were also another related feature we were discussing, which might be good to consider when building this out.

**Comment by kindlyseth** [comment]
Someone in Slack mentioned another attack vector that should be blocked by this feature: the case where Slack might be compromised in a way allowing impersonation of an authorized Slack user.

**Comment by kindlyseth** [comment]
Someone in Slack mentioned another attack vector that should be blocked by MFA support: the case where Slack might be compromised in a way allowing impersonation of an authorized user.

**Comment by kindlyseth** [comment]
May be relevant to design decisions: https://slack.engineering/distributed-security-alerting-c89414c992d6

**Comment by jesselang** [comment]
This would be a nice feature, but I don't think there's a clear direction on how and where this would be implemented. An out-of-band confirmation could certainly be handled without Cog's help. The community is focusing on some core features. Perhaps we'll be able to return to this at some point in the future.
