### ISSUE TITLE
Piper incorrectly parses `#test` as a boolean followed by `est`

### ISSUE THREAD

**Issue by vanstee** [operable/cog#328]
Fix this so `#test` is parsed as a string rather than a boolean followed by a string. Seems like a word boundary whitespace issue.

**Comment by mpeck** [comment]
dependent on #340

**Comment by vanstee** [comment]
This seems to have already been fixed. `#test` and even `#t` are both now parsed as strings. `true`, `TRUE`, `false`, and `FALSE` are the only allowed boolean values.
