### ISSUE TITLE
Does `-` denote flag or negative number?

### ISSUE THREAD

**Issue by lhaskins** [operable/cog#33]
Currently, the `-` is parsed as a flag indicator, but it can also mean negative number. We need to be able to parse our commands such that they will know the difference.

In other words, if a command does not have an option defined as `-<some number>`, then treat it as a negative number.

Example:
`sum 2 -9` should be interpreted as 2 + -9 We currently have to say `sum 2 "-9"` in order for `-9` to not be interpreted as a flag.

**Comment by mpeck** [comment]
dependent on #340

**Comment by vanstee** [comment]
Looks like this was fixed in #159
