### ISSUE TITLE
Refactor bundle JSON validation

### ISSUE THREAD

**Issue by lhaskins** [operable/cog#339]
The bundle validation code currently uses try/rescue clauses to handle any validation issues in the bundle config.json files. We should explore using JSON schema validation (https://github.com/for-GET/jesse) and clean this up to use :ok/:error return values.

**Comment by imbriaco** [comment]
Let's hold off on doing this for the time being since we want to revisit the bundle configuration file format anyway. I'd rather not invest more time than we have to into the existing JSON stuff.
