### ISSUE TITLE
Piper updates

### ISSUE THREAD

**Issue by mpeck** [operable/cog#340]
General rework on piper in preparation for the executor re-write. This may also fix some of the other outstanding parser issues.

**Comment by kevsmith** [comment]
### Motivation

Fixes for #328, #324, and #33 for sure. Possibly fix #251 as well.

### Objective

Stabilize Cog's command parsing behavior and provide a foundation for future development. Incorporate lessons learned from previous 2 parsers.

### Plan

- [ ] Write new lexer and parser using `leex` and `yecc`. These tools are better tested than our hand rolled versions and handle a number of edge cases much better than ours. This will likely require a parallel AST implementation to supplant the current one.
- [ ] Ensure new lexer and parser pass Piper's existing test suite for lexing, parsing, and variable binding.
- [ ] Port executor to use new parser and AST.

**Comment by kevsmith** [comment]
Work will be PR'd with PRs for #286
