### ISSUE TITLE
Rules for routing invocations to specific Relays

### ISSUE THREAD

**Issue by christophermaier** [operable/cog#349]
Create the ability to define rules governing which relay a command is invoked on. Think of running EC2-related commands from a relay in a specific network for your production infrastructure vs. test or dev.

Would require human-readable names / labels / tags for relays, instead of UUIDs.

Current idea is to define rules similar to our command rules for this.

**Comment by kevsmith** [comment]
No plans to implement this in the next 3 months. Closing.
