### ISSUE TITLE
General config validation

### ISSUE THREAD

**Issue by mpeck** [operable/cog#359]

**Comment by mpeck** [comment]
We do quite a bit of config validation which currently a bit spread out. I'm thinking that we can consolidate that into a general lib. @vanstee did a good bit of work on the adapter config validation. We can pull some of that into the lib. Additionally we might take some inspiration from Clojure's schema lib (https://github.com/plumatic/schema).

**Comment by kevsmith** [comment]
Building a library means you're solving a problem or satisfying a set of requirements. This issue should be about "validating Cog config", "generating better error messages", etc. Jumping right to building a library without understanding why is getting the cart before the horse.

**Comment by kevsmith** [comment]
Don't research this issue until it includes a clear problem description.

**Comment by mpeck** [comment]
I think I may have actually jumped the gun on creating this ticket.
