### ISSUE TITLE
Optional first and last names for users

### ISSUE THREAD

**Issue by lhaskins** [operable/cog#362]
When creating a user via the API, the user's first name and last name are not required fields. We should be able to create a user without these fields.

**Comment by lhaskins** [comment]
Only the username, email address and possibly password are required. The email is required since it will be used by Flywheel when setting up Cog in the first place. For the password, it is possible to make this optional and if the user doesn't supply a password, we randomly generate one for them.

**Comment by lhaskins** [comment]
This change does require a change to the database to allow for null first_name, last_name values.

**Comment by vanstee** [comment]
LGTM. Might be worth changing the name of this issue to something like "Optional first and last names for users"

**Comment by lhaskins** [comment]
Will do. Thanks!

**Comment by lhaskins** [comment]
Passwords will continue to be a required field.

**Comment by kevsmith** [comment]
This issue isn't ready for work and should never have cleared research review for the following reasons:

1. No clear statement of requirements or problem
1. No task checklist of work to be done
1. All of the relevant info is strewn across multiple comments which makes it difficult to comprehend instead of the issue description where it belongs.

Moving back to research until these points are addressed.

**Comment by lhaskins** [comment]
### Motivation
We should be able to create a user with only a username and email_address during the signup process.  

### Objective
We should be able to create new users by only supplying a minimum set of data.

### Research
Exploring where Cog sets and requires first_name and last_name usage and if it would make sense to also make passwords optional. 

### Plan
The first and last names are not used for anything related to the use of Cog. It is informative data. These can be optional fields. 

The password would be used for cogctl (and eventually the web UI). Initially the first password used upon setup is generated. We then use that to get a token for use with the API. That said a user will need their password each time they attempt to run a command using cogctl. As a result, the password should continue to be a required field.

Tasks
- [ ] Update the database to allow for null first_name, last_name values.
- [ ] Update the User model to make first_name, last_name optional fields
- [ ] Update cogctl to reflect the optional fields for the users call
