### ISSUE TITLE
Bundle install fails if pending directory is on different filesystem

### ISSUE THREAD

**Issue by imbriaco** [operable/cog#374]
If the `pending` and `bundles` directories are on different filesystems, Bundle installation will fail. This is because we use `File.rename` (wrapper for `rename(2)`)  which will return `{:error, :exdev}` when we try to create a cross-device link, at least on Linux.

This happens in Relay for locking simple bundles, here:
https://github.com/operable/relay/blob/f398dab1f2c84fe868f384966064a5d4912caa13/lib/relay/bundle/install_helpers.ex#L176

We use `File.rename` for a number of other bundle related actions which will also fail if the source and destination happen to be on different filesystems.

Rather than replace occurrences of `File.rename` with a function that falls back to copy + delete, I think we should just require all bundle related directories to be on the same filesystem and document this accordingly in a comment in `config.exs` and potentially in the Wiki.

**Comment by vanstee** [comment]
We're no longer using `pending` and `bundles` directors for bundle installation.
