### ISSUE TITLE
Need I make a .json file for sample bundle installation?

### ISSUE THREAD

**Issue by rebyn** [operable/cog#375]
I've followed the steps [here](https://github.com/operable/sample_simple_bundle#sample-simple-command-bundles) until step 5. I placed `ping.yaml` in Relay's `/home/operable/relay/data/pending`.

I've been waiting for Relay to detect this new file and install yet nothing came up so far.

In this [guide](https://github.com/operable/cog/wiki/Managing-Bundles), it was written that:

`If you want to install a bundle, simply place the bundle file (a .cog file for a standard bundle, or a .json file for a simple bundle) in this directory and within a few seconds (this period is configurable as well), Relay will install it!`

What would be the content of this .json file (can I ask for a sample?) and do I need it for Relay to install `ping.yaml`?

Thanks!

**Comment by mpeck** [comment]
Our configs used to be in `.json`. We just switched to `.yaml` recently. You may have a mismatched version. Make sure everything is up to date with master and try again. I'll update the guide and remove the reference to json.

**Comment by rebyn** [comment]
Thanks. I've been using the provided Docker images and thus am not sure how far it is behind. Do you have automated builds behind these images or they're all built manually?

**Comment by mpeck** [comment]
Right now images are built manually. Our release process is one of the high priority items our list as we work towards 1.0. We are planning to release 0.3 soon and will iterate on the process for that.

**Comment by vanstee** [comment]
Closing as we've updated everything to use yaml, and we already have issues around the bundle config generation story. Let us know if you still need help @rebyn.
