### ISSUE TITLE
Document log handling behavior

### ISSUE THREAD

**Issue by imbriaco** [operable/cog#38]
Need to fully document TolerantFile behavior:
- Describe file lifecycle and `stat()` calls
- Explain behavior when log file is moved
- Describe recommended approach for log rotation (ie: just move the file, cog will make a new one)

**Comment by vanstee** [comment]
I'm not sure we're still using the `TolerantFile` module in our codebase anymore.

**Comment by christophermaier** [comment]
We do; it's in `probe`: https://github.com/operable/probe/blob/master/lib/probe/tolerant_file.ex

**Comment by vanstee** [comment]
D'oh thanks @christophermaier.

**Comment by christophermaier** [comment]
This issue was moved to operable/cog-book#91
