### ISSUE TITLE
Run Cog in the prod env

### ISSUE THREAD

**Issue by vanstee** [operable/cog#380]
The default config we have for dev is not always the best config for running Cog in a production env (spoken commands, log levels, etc), so we should start running Cog with `MIX_ENV=prod`.

This means all of our installation docs, startup scripts and docker setup should all run Cog in the prod env. We should also double checking that the base prod config has sane vars, since I don't think it has been used yet.

**Comment by vanstee** [comment]
@kevsmith Did we fix this with the 0.5 release?

**Comment by christophermaier** [comment]
Pretty sure we do this now.
