### ISSUE TITLE
Event Hook REST API & Data Model

### ISSUE THREAD

**Issue by kevsmith** [operable/cog#385]
- [ ] Define `event_hook` table schema
- [ ] Define Ecto model
- [ ] Create Ecto migration
- [ ] Create `EventHookController`

See #344 "Managing event hooks" for details.

**Comment by christophermaier** [comment]
This would be a fine time to start incorporating JSON Schema-based validation to incoming API request bodies. It also has the nice side effect of providing some machine-readable documentation for the API.
