### ISSUE TITLE
Event Hook Endpoint

### ISSUE THREAD

**Issue by kevsmith** [operable/cog#387]
### Summary

The event hook endpoint should be a separate Cowboy listener ([docs](http://ninenines.eu/docs/en/cowboy/HEAD/guide/introduction/)) which accepts requests for routes shaped like `/event_hooks/1581880e-c337-45cc-a1ec-7a09be2f6612` where the UUID is the unique id of a event hook definition. Listen address and port should be configured in Cog's config file. The config should be smart enough to use environment variables for these values if the variables exist.

Internally the endpoint should look like another chat adapter to allow for hook-specific output templates and easy integration with existing pipeline execution infra.

### External event handling step-by-step

1. Does the URL root begin with `event_hooks`?
  - No: Return 404.
  - Yes: Continue.
1. Is the id a valid UUID?
  - No: Return 400 and "Event hook ids must be valid UUIDs" message.
  - Yes: Continue.
1. Does a event hook exist with the given id?
  - No: Return 404.
  - Yes: Continue.
1. Does the user pointed to by `as_user` exist?
  - No: Return 422 and "The user associated with this event hook does not exist" message.
  - Yes: Continue.
1. Is the request's HTTP verb listed in the hooks `verbs` field?
  - No: Return 400 and "Method XXX not supported. Supported HTTP methods are X, Y, Z" message.
  - Yes: Continue.
1. Assign the request a unique request id.
  - `:erlang.monotonic_time/0` is sufficient for initial implementation
1. Create initial calling arg map.
  - Add request parameters, if any, to the map.
  - Gather any headers specified in the hook's `capture_headers` field into a map. Add this map to the args map with the name `headers`. If none match or the hook definition contains none use an empty map as a placeholder value.
  - If a request body exists, add it to the args map with the name `body`.
1. Create a new `Spanner.Command.Request` using the retrieved user as `requestor`, the map built in step 7 as `args`, and a `reply_to` containing a MQTT topic string like so: `event_hooks/<hook_id>/<request_id>`.
1. Send the constructed request to the executor
  - If the pipeline succeeds return a 200 and use any pipeline output returned as the response body.
  - If the pipeline crashes send a 500 and the error message returned by the executor.

### To Dos
- Define how to route executor messages sent via `reply_to` topic to the correct Erlang process.

Part of #344

**Comment by christophermaier** [comment]
With the new executor, I don't think we'll need to mess around with `Bindable` et al. I currently seed _all_ pipelines with an empty map for binding purposes (keeps downstream implementation uniform). We'll just need to create a plain old map (or maps!) and use _that_ instead of the empty map to seed things.

**Comment by kevsmith** [comment]
Updated to reflect @christophermaier's comments and use existing request dispatch to simplify implementation. Also called out a design to do which needs to be solved prior to or during implementation.
