### ISSUE TITLE
failed to start child: Cog.Adapters.Slack.Sup

### ISSUE THREAD

**Issue by jason-riddle** [operable/cog#392]
Getting the following stack trace when trying to run this with docker-compose.
```
cog_1      | =INFO REPORT==== 16-Mar-2016::18:52:06 ===
cog_1      |     application: logger
cog_1      |     exited: stopped
cog_1      |     type: temporary
cog_1      | ** (Mix) Could not start application cog: Cog.start(:normal, []) returned an error: shutdown: failed to start child: Cog.Adapters.Slack.Sup
cog_1      |     ** (EXIT) shutdown: failed to start child: Cog.Adapters.Slack.RTMConnector
cog_1      |         ** (EXIT) an exception was raised:
cog_1      |             ** (MatchError) no match of right hand side value: {:error, %HTTPoison.Error{id: nil, reason: :closed}}
cog_1      |                 (cog) lib/cog/adapters/slack/rtm_connector.ex:36: Cog.Adapters.Slack.RTMConnector.start_link/3
cog_1      |                 (stdlib) supervisor.erl:343: :supervisor.do_start_child/2
cog_1      |                 (stdlib) supervisor.erl:326: :supervisor.start_children/3
cog_1      |                 (stdlib) supervisor.erl:292: :supervisor.init_children/2
cog_1      |                 (stdlib) gen_server.erl:328: :gen_server.init_it/6
cog_1      |                 (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
cog_cog_1 exited with code 1
```

I've exported the following.

```bash
COG_ADAPTER="slack"
SLACK_API_TOKEN="<snipped>"
POSTGRES_USER="user"
POSTGRES_PASSWORD="password"
```

Not sure on how else to debug this?

**Comment by jason-riddle** [comment]
So I think the problem was I was behind a proxy when I was trying to run this. Does cog respect the <code>http_proxy</code> and <code>https_proxy</code> variables?

**Comment by mpeck** [comment]
Hmm, I don't think it does. @imbriaco can you shed any light on that?

**Comment by vanstee** [comment]
@jason-riddle Cog itself does not, but since you're running Cog inside of docker already would using docker's http proxy support work?

Creating a new machine with `HTTP_PROXY` and `HTTPS_PROXY` env vars should work.

```
$ docker-machine create -d virtualbox \
  --engine-env HTTP_PROXY=http://<host>:<port> \
  --engine-env HTTPS_PROXY=https://<host>:<port> \
  proxy-machine
$ eval "$(docker-machine env proxy-machine)"
$ POSTGRES_USER=<postgres-user> POSTGRES_PASSWORD=<postgres-password> COG_ADAPTER=slack SLACK_API_TOKEN=<slack-token> docker-compose up
```

**Comment by imbriaco** [comment]
Also be aware that the proxy probably needs to support websockets since the Slack RTM API that we rely on is delivered via websocket connections.

**Comment by jason-riddle** [comment]
@vanstee Using <code>--engine-env</code> only configures docker engine, which is used to pull docker images, login to docker hub, etc.

@imbriaco Hmm.. that's an interesting point. I don't know if our proxy does support websockets but if it does not then this might not be a non-starter for me.

**Comment by vanstee** [comment]
D'oh, you're right. Sorry about that.

I added a [new issue](https://github.com/operable/cog/issues/528) to add support for running Cog behind a proxy. But right now we're focused on releasing 0.4.0 so I'm not exactly sure when we'll start working on this.

**Comment by vanstee** [comment]
Closing in favor of https://github.com/operable/cog/issues/528
