### ISSUE TITLE
Memory Service

### ISSUE THREAD

**Issue by kevsmith** [operable/cog#396]
See http://docs.operable.io/v0.4/docs/services#section-memory-service

**Comment by kevsmith** [comment]
Depends on #358

**Comment by vanstee** [comment]
# High-level design

The memory service will follow from a lot of design work done in #358. The memory service is supervised by a `Command.Service.Supervisor` and stores it's data in a shared ets table. Each time a request comes in we'll use the token and key to look up the item in storage. If we're storing new data, we'll ask the `Serivce.Tokens` for the owning pid and then also monitor that pid from the `Service.Memory` so we can clean up after the pipeline is over. The API routes will be under the same plug that requires a token.

# API Semantics

* Getting an unset key results in a 404
* Accumulating with an unset key pushes the value into an empty list.
* Accumulating with a key containing a non-list results in a 422 error.
* Deleting an unset key results in a 404

**Comment by vanstee** [comment]
I was curious about potentially having a memory service process per executor process but since we'd need a global registry to lookup a memory process from a service token, I think it's worth waiting until we have multiple services implemented to switch something like that.

**Comment by vanstee** [comment]
Done as of https://github.com/operable/cog/pull/587
