### ISSUE TITLE
Handle command template rendering errors

### ISSUE THREAD

**Issue by kevsmith** [operable/cog#397]
The pipeline executor will crash if rendering a template throws an error. Instead it should log the error, along with contextual information about the error (pipeline id, requesting user, template and bundle which triggered the error), and return a human-friendly error message to the user.

**Comment by mpeck** [comment]
If we crash when rendering a template, do we fail the pipeline?
I'm wondering if we should return the results of the pipeline to the user along with a message explaining the failure to the user?

**Comment by kevsmith** [comment]
The executor process goes away which I think counts as pipeline failure. Unsure if we should send the results or not. Gets tricky if they exceed a chat provider's max message size.

**Comment by mpeck** [comment]
I say let's just return the error message to the client and drop the results. I think that's the path of least resistance. If it becomes an issue, we can revisit later. Thoughts?

**Comment by mpeck** [comment]
## Motivation
If we crash during template rendering the executor crashes and the user receives no feedback.

## Objective
When template rendering crashes we should `rescue`, log an appropriate error, respond with a human readable message to the user and fail the pipeline.

## Plan
The new executor refactor makes this a pretty simple fix. When the template is rendered, https://github.com/operable/cog/blob/95ab100c0c8b48995eb478564ffc7866c076c9ea/lib/cog/command/pipeline/executor.ex#L397, we can just `rescue` and fail gracefully.

```
...
try do
  fun.(context)
rescue
  error ->
    Logger.error(<nice error message>)
    Helpers.send_error(msg, state.request, state.mq_conn)
    fail_pipeline()
end
...
```
