### ISSUE TITLE
Remove vestiges of Carrier signatures

### ISSUE THREAD

**Issue by imbriaco** [operable/cog#401]
In #400, we stubbed out the calls in carrier that referred to `enacl` and removed that dependency. We need to go through cog, relay, spanner, and carrier and remove the rest of the signature related dead code.

**Comment by mpeck** [comment]
## Motivation
We no longer have a need for libsodium and likewise enacl. This removes the need for erlang to be compiled with dirty schedulers which has caused many headaches. To facilitate the move calls to enacl were stubbed out in a previous issue, #400. We need to finish the clean up.

## Plan
I'm thinking that we can remove the stubs from carrier and work our way up the dependency list removing all their references.

[ ] Remove stubs from carrier
[ ] Validate the tests for carrier still pass
[ ] Bump the carrier dep in spanner and remove all references to the old calls
[ ] Validate the spanner tests pass
[ ] Bump the spanner dep in cog and remove any references
[ ] Validate the cog tests pass

**Comment by christophermaier** [comment]
@mpeck Don't forget Relay, too

**Comment by mpeck** [comment]
oh good point
