### ISSUE TITLE
Add context to what happens during the bootstrap action

### ISSUE THREAD

**Issue by vanstee** [operable/cog#406]
@bmontague mentioned that it wasn't clear what happened during the bootstrap action. It would be nice if users were notified that we created an admin user for them and stored the credentials in `~/.cogctl`.

To inform our users what happens during bootstrapping and reveal a bit about how cogctl works, lets have `cogctl bootstrap` print the following on a successful bootstrapping.

```
$ cogctl bootstrap
Created admin user

ID        .*                                                                                                         
Username  admin
Password  ********

Created profile at ~/.cogctl

Host      localhost
Password  ********
Port      4000
Secure    false
User      admin

Bootstrapped cog
```

**Comment by christophermaier** [comment]
This issue was moved to operable/cogctl#136
