### ISSUE TITLE
Support '.yml' and '.yaml' extensions

### ISSUE THREAD

**Issue by mpeck** [operable/cog#413]
Config files are in YAML. Currently we only support files with the `.yaml` extension. Since YAML files can also have a `.yml` extension, we should support both.

**Comment by mpeck** [comment]
## Motivation
Even though `.yaml` is the official extension some folks use `.yml`. We should support both to make it as easy for our users as possible.

## Objective
Support both `.yaml` and `.yml` in an easily maintainable and modifiable way.

## Research
There are several spots that will need some work to support multiple file extensions. Most concern relay. Both `Relay.Bundle.Installer` and the `Relay.Bundle.Scanner` depend on knowing the correct file extension. Additionally there are several places scattered throughout relay that reference config file extensions.

`Relay.Bundle.Scanner` only references the extension in one function `pending_bundle_files/0`. `Path.wildcard` supports alternates, http://elixir-lang.org/docs/stable/elixir/Path.html#wildcard/2, so it should be an easy fix for the scanner.

`Relay.Bundle.Installer` is a bit more complicated. We often use the pattern of checking if a path string ends with the config file extension to make decisions about what work to be done, example: https://github.com/operable/relay/blob/599299d9592c402172d3a9850fdf9027288ca78d/lib/relay/bundle/installer.ex#L65. I think we can shift some of that logic to spanner and simplify things a bit.

## Plan
We need to add some utilities to spanner to help us identify what type of bundle is being installed. Spanner should also return a list of file extensions that we support for config files. Relay will then need to be modified to accept a list of said extensions and act accordingly.

- [ ] Add helper functions to spanner for bundle identification
- [ ] Have spanner return a list of supported extensions
- [ ] Update relay to work with the new spanner utility function/s and list of extensions

**Comment by vanstee** [comment]
@mpeck Should we also silently support the `.json` extension since that is also technically YAML?

**Comment by mpeck** [comment]
It should be easy to add `.json` along with `.yaml` and `.yml` :+1:
