### ISSUE TITLE
complete install through apt-get, for ubuntu 14.04 (with dependencies)

### ISSUE THREAD

**Issue by ketzacoatl** [operable/cog#439]
Following https://github.com/operable/cog/wiki/Installation-Guide, I started exploring `cog` with the Docker images. That worked great, and I was able to complete my initial explorations of the system integrated with Slack (it's _awesome_, a totally great product!). While I can easily run the cog server as an instance on Docker, for various reasons, it makes a lot of sense in my infrastructure for the cog relay to run directly on the host (not on Docker). That led me to the question: _how do I install cog-relay on Ubuntu 14.04?_

Going back to the install guide, the non-docker options are: either running the git/make directly ("manual install") or using the `setup.sh` script (https://github.com/operable/cog/blob/master/scripts/setup.sh, the "scripted install"). It seems the `setup.sh` assumes the user will install elixir and the other dependencies:

```
user@host:~# ./setup.sh                                                                                                                                                          
Erlang installed.....Not found
Elixir installed.....Not found
Mix installed.....Not found
Make installed...../usr/bin/make
Git installed...../usr/bin/git
Setup aborted.
```

As a user looking to test out the system and get functional configuration management formula in place, this is my first contention: your installation guide, the script.sh, etc, should provide the guidance needed to setup/install the dependencies cog will need.

Now is probably a good time to mention that I'm ok with a rough product, and something being sharp won't keep me away.. I'm just sharing the critical perspective, assuming it will be helpful.

The second contention I experience with the existing methods, is that the "scripted install" (`script.sh`) appears to run through the manual build, rather than installing packages. As a user interested in getting up and running quickly, but also requiring some conventions (and flexibility) from my tools, I would like to request the following:
- it should be possible to install cog, and all its dependencies, with `apt-get`
- the install guide should inform the user how to install the dependencies, or point the user to the information they should follow
- it's great to have the manual install scripted, but if all deps and cog itself are installable through `apt-get`, a script that grabs/imports the GPG key and installs the packages correctly is invaluable (to both newbs who want something quick, as well as experts who need to know what to have config management reproduce).

Digging into the build process for the Docker image, it seems the apt-get appears available, and I attempted installing packages with the help of https://github.com/operable/docker-base/blob/master/packagecloud.sh, but that did not work.

I eventually followed http://elixir-lang.org/install.html to install elixir, then ran `setup.sh`, but that fails:

```
user@host:~# ./setup.sh -v /usr/local/bin/
Erlang installed...../usr/bin/erl
Elixir installed...../usr/local/bin/iex
Mix installed...../usr/local/bin/mix
Make installed...../usr/bin/make
Git installed...../usr/bin/git
Cloning repositories for the following projects: cog relay cogctl relayctl

Cloning into 'cog'...
remote: Counting objects: 4477, done.
remote: Compressing objects: 100% (149/149), done.
remote: Total 4477 (delta 131), reused 62 (delta 62), pack-reused 4259
Receiving objects: 100% (4477/4477), 2.30 MiB | 2.91 MiB/s, done.
Resolving deltas: 100% (2448/2448), done.
Checking connectivity... done.
Note: checking out '0.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 1d6c0f0... Updating internal deps
Building cog.
Makefile:38: *** Erlang must be compiled with support for dirty schedulers.  Stop.
cog build failed.
Setup aborted.
```

```
user@host # elixir --version
Erlang/OTP 18 [erts-7.3] [source-d2a6d81] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.2.3
```

**Comment by vanstee** [comment]
This is a great idea and something we need to do before a 1.0 release of Cog. Thanks for dealing with all the rough edges and sending us detailed feedback. We might not get to this right away, but I'm going to tag this with 1.0 so we remember to come back to it.

**Comment by christophermaier** [comment]
Closing due to age
