### ISSUE TITLE
Handle HipChat redirects according to their platform convention

### ISSUE THREAD

**Issue by christophermaier** [operable/cog#443]
Similar to #210, we should adhere to the conventions of HipChat when resolving redirects.

HipChat user mentions are prefixed with an "@", just like in Slack, so that's fine. Room mentions are not, as far as I can tell, an actual "thing" on HipChat, and so our current imposition of "#" for room mentions may be fine (in that you can't really conflict with something that doesn't exist), or we may want to remove that; a redirect that isn't prefixed with "@" would thus be treated as a room name.

(However, this should be weighed against the possible conflicts for HipChat channels named "me" and "here", our two current "special" redirects).

Related is HipChat's special `@all` and `@here` mentions. If these are used as a redirect target, the pipeline would fail; these would be looked up as user names and would fail. These should probably end up resolving to the equivalent of our `here` redirect keyword. (Bonus points for a message that informs users that they probably don't really want to "redirect" to `@all` or `@here`.)

See https://confluence.atlassian.com/hipchat/get-teammates-attention-744328217.html for more about HipChat's mention capabilities.

**Comment by vanstee** [comment]
We decided to sticking to `#room_name` and `@user` for these conventions along with `here` and `me` special redirects.
