### ISSUE TITLE
Docker support for relay commands

### ISSUE THREAD

**Issue by bigbam505** [operable/cog#447]
It would be very cool to have commands from the relay have the potential to run inside docker images.  Not sure if it makes sense to just build them on the relay or just allow them to be run but either way it could allow for a much easier way to run commands that have dependencies.  Not sure the best way to integrate this or if it's possible because relay itself could be in a docker image itself

**Comment by imbriaco** [comment]
This was such a good idea that we went ahead and built it. :)
https://blog.operable.io/announcing-cog-0-4-2713babf1c3b#.f0xa9w8e7

Thanks for the suggestion!
