### ISSUE TITLE
Simplify Cog permission model

### ISSUE THREAD

**Issue by imbriaco** [operable/cog#452]
# Overview

In an effort to make the permission model more accessible, we're going to simplify the model that we expose to users. The simplified model looks like this:

- **Permissions** may only be assocaited with **Roles**.
- **Roles** may only be associated with **Groups**.
- **Groups** may only be associated with **Users**.

That means we will remove the following:

- **Permissions** can no longer be attached directly to **Groups** or to **Users**. They can only be associated with **Roles**.
- **Groups** can no longer contain other **Groups**.

# Implementation

From an implementation point of view, we will not immediately change the data model in Cog, we will only make changes to what is exposed via the REST API and, by extension, `cogctl`.

- [x] Remove routes to API endpoints for the deprecated functionality.
- [x] Update remaining REST API endpoints to remove access to the deprecated functionality. This may involve things like filtering group-within-group relationships from the `GET /v1/groups/:id/memberships` route and disallowing those sorts of relationships to be created in `POST /v1/groups/:id/membership`. These are just a couple of examples but all the user/group/role/permission related endpoints need to be evaluated.
- [x] Update cog-api-client to match the REST API changes above.
- [x] Update cogctl to match the REST API changes above.

**Comment by kevsmith** [comment]
This is done, yeah?

**Comment by imbriaco** [comment]
Yep, good catch. Closing.
