### ISSUE TITLE
Rewrite the TemplateCache to expose "core" templates

### ISSUE THREAD

**Issue by christophermaier** [operable/cog#469]
The current `TemplateCache` is tightly coupled to our adapters (specifically the Slack and HipChat adapters), as well as to our "embedded" templates (`raw`, `text`, and `json`).

To remedy this, we should create the notion of a "core", or bundle-independent, template. Current real templates are tied to bundles, but things like `raw`, `text`, and `json` are general-purpose templates, dependent only on the adapter being used. We'll need to devise a way to store these in the database. Since these are effectively embedded templates, we don't need to worry about providing a way for users to manipulate the templates (e.g. install their own).

Additionally, logic for template "fallback" is currently embedded in the executor. For instance, if a command has declared that its output should be formatted with the "foo" template, but no "foo" template exists for the current chat adapter, we can fall back to one of the embedded templates. This should be incorporated into the main template lookup logic. This also implies that in addition to supplying "core" templates for each of our adapters, we should also provide a bare-bones fallback template for "any" adapter. This ensures that any adapter will be able to generate output, whether or not it has a template that's been tailored to it.

Since the current system is built around anonymous functions that perform the actual template rendering, we can also simplify the executor a bit by baking error-recovery into these template functions. Eventually, we'll want to incorporate our error messaging into templates, and this error-recovery probably helps get around the interesting situation of how you display an error rendering an error template. (It may also be necessary to do something like implementing core template fallbacks as code to provide some stable "base case" for situations like this.)

Finally, the interface that the executor retrieves templates from should not indicate anything about it being implemented in terms of a cache. That is an implementation detail, and the executor shouldn't need to change if we remove the cache, or dramatically alter its implementation.

The cache implementation itself could be simplified, as well; take a look at https://github.com/operable/cog/blob/2ac109995e0a996783ceacff5a4e81af230b3d8b/lib/cog/command/bundle_cache.ex for suggestions / patterns.

**Comment by vanstee** [comment]
Plan of action:

- [ ] Move template code out of executor into Template module with cache related API stuff hidden away
- [ ] Use a function partial (new feature for fumanchu) to render json from a mustache template
- [ ] Store templates in the database and look them up on demand
- [ ] Add "any" fallback templates
