### ISSUE TITLE
Building Cog & Relay instructions

### ISSUE THREAD

**Issue by kevsmith** [operable/cog#47]
- Development tool prerequisites:
  - Erlang R18B01 or later
  - Elixir 1.2 or later
  - Postgres 9.4 or later
- Getting the source for Cog and Relay
- Building Cog and Relay
- Starting it up for the first time
- Pointers to:
  - Design docs
  - "How to contribute" docs

**Comment by lhaskins** [comment]
It seems like we have all of these bases covered. They aren't exactly organized in this manner, but the main Wiki page allows one to navigate to get to each area in this list. Or am I missing something?

**Comment by mpeck** [comment]
@kevsmith can you confirm that this is finished or is there more work to be done?

**Comment by kevsmith** [comment]
Do we have accurate instructions in the wiki? If so, then we can close.
