### ISSUE TITLE
Extract error templates from the executor

### ISSUE THREAD

**Issue by christophermaier** [operable/cog#470]
_Depends on #469_

Currently the Executor has three error messages that it hard-codes:

* the message shown to users that don't have either a Cog account or a registered chat adapter handle 
* the error message shown whenever redirect targets are found to be invalid
* the general error message shown whenever another failure in pipeline processing ocurrs (once #468 merges, that is)

Once issue #469 is complete, each of these should be extracted from the executor and turned into proper error templates.

**Comment by vanstee** [comment]
Would there be any utility in moving the generic errors into a template as well, now that we can render json?

**Comment by christophermaier** [comment]
Maybe? Those are mainly to create a human-readable message which we then stick into the larger error message with all the additional context. I'm not sure yet if they merit their own templates. How about we see what it's like with these three "big ones", and see what things look like afterward?
