### ISSUE TITLE
Extend permission system refactoring completely throughout the system

### ISSUE THREAD

**Issue by christophermaier** [operable/cog#493]
Work has already begun to simplify our permission system. User-facing API changes have been made in https://github.com/operable/cog/pull/492, but this still leaves code in the core of the system that is effectively dead. In order to complete the permission system refactoring, we need to remove this code, extra model modules that are no longer needed, simplify / remove related stored procedures, etc.

**Comment by vanstee** [comment]
@christophermaier Has this already been done?

**Comment by vanstee** [comment]
There's still refactoring to do on the groups and roles side of things. Closing in favor of https://github.com/operable/cog/issues/1191
