### ISSUE TITLE
Bundle config format versioning

### ISSUE THREAD

**Issue by mpeck** [operable/cog#497]
# Motivation
Cog should continually be changing to support newer and better technologies. For example eventually we hope to support bundle types other than simple and docker. In order to do that one thing we need is a way to version our config formats.

# Objective
To provide a means to easily version config files.

# Early Research
tl;dr These are some early thoughts regarding versioning. It's entirely possible that this could all change. But to summarize, the key take away is as follows:
* leverage json schema
* add functionality to json schema allowing for arbitrary validation functions
* remove custom validation logic from spanner

Currently we are leveraging JSON schema and some custom logic to handle config validation. If we could remove our custom logic and fully leverage JSON schema, we should be able to easily update schemas as necessary with relatively little friction. 

The main issue with using just JSON schema to validate configs revolves around our need to validate rule parsing. JSON schema provides mechanisms for validating that a rule is a string and can even validate based on a regular expression, but we need to go further. We need to verify that rules can be parsed without error. We do this now by pulling rules out of the config after JSON schema validation and parsing them. This is a bit brittle, because it is necessary that we know where in the config rules appear in order to validate them. One possible solution is to patch the JSON schema lib we are using, ExJsonSchema, to accept an arbitrary validation function. This does break the JSON schema standard, but for our use case it may be the best option.

**Comment by vanstee** [comment]
Config formats have already been versioned as part of the switch to yaml IIRC.
