### ISSUE TITLE
Deploying, assigning, and enabling a bundle should be done in one step

### ISSUE THREAD

**Issue by kevsmith** [operable/cog#534]
At present there are too many discrete steps required to deploy a bundle to a useful state.

It should be possible to deploy, assign, and enable a bundle in a single `cogctl` invocation like so:

`cogctl bundles create --enable --groups=test1,test2 /path/to/config.yaml`

**Comment by vanstee** [comment]
As part of this, it would be great if we printed the current enabled/disabled status after creation just to reinforce what happened. For instance, if you forgot the `--enable` flag you wouldn't know until you ran the command and saw that it wasn't installed yet.

**Comment by vanstee** [comment]
Here's a break down of what I have planned here.

* [ ] Add optional `--enable` flag (disabled will remain the default)
* [ ] Add optional `--relay-groups` flag that accepts a list of group names
* [ ] Explain all actions taken (Created bundle, enabled bundle, added bundle to groups) and then print full list of attributes for the bundle installed

**Comment by imbriaco** [comment]
:+1: this sounds great.
