### ISSUE TITLE
Allow users to provide their own relay uuid

### ISSUE THREAD

**Issue by kevsmith** [operable/cog#537]
The current design where Cog is the sole authority on Relay IDs complicates bootstrapping new Cog installs in dynamic environments like EC2, GCE, Docker, and the like. It requires the user to have set up Cog and gotten in running before they can configure a Relay.

Since our only requirement is that Relay IDs must be unique among all Relays for a given Cog instance I believe we can support allowing users to specify their own Relay ID's as long as Cog enforces the ID is a valid UUID and is unique amongst all Relays known by that Cog instance.

If an ID is not provided then Cog should continue its current practice of generating a UUID.

The `cogctl` invocation could look like this:

`cogctl relays create --id 923A6788-2E76-4201-B6CB-E72B0E2CEA19 --name test1 --token sekrit`

where `--id` is optional.

**Comment by vanstee** [comment]
* [x] Add support to the API for providing an id
* [ ] Add support to cogctl for providing an id that's passed to the API

**Comment by vanstee** [comment]
Finished via

https://github.com/operable/cog/pull/560
https://github.com/operable/cogctl/pull/56
