### ISSUE TITLE
Protect admin group and role from modification

### ISSUE THREAD

**Issue by imbriaco** [operable/cog#543]
Now that we're creating an administrative role and group during bootstrap which we rely on for administrative access, we need to ensure that they cannot be deleted. A PR will follow this which handles this in two ways:

1. By adding constraint triggers in the database to protect those rows.
2. By returning useful errors when attempts to delete those rows are made via Ecto or the API.

**Comment by kevsmith** [comment]
We should do the same thing for the `operable` bundle, too.

**Comment by imbriaco** [comment]
Good call, I'll do that in my PR too.

**Comment by imbriaco** [comment]
This was fixed in #551 and #555.
