### ISSUE TITLE
Speed up cogctl's tests

### ISSUE THREAD

**Issue by mpeck** [operable/cog#563]
cogctl takes forever to run it's tests. It's also very prone to false negatives. We should implement something like exVCR to improve the dev experience.

**Comment by mpeck** [comment]
The following resources will need updates to implement ExVCR:
- [x] bundles
- [ ] users
- [ ] chat handles
- [ ] permissions
- [ ] relays
- [ ] relay groups
- [ ] roles
- [ ] rules
- [ ] triggers
- [ ] bootstrap

**Comment by vanstee** [comment]
This is an on-going process as we rewrite sections of cogctl. Closing this for now.
