### ISSUE TITLE
Fix bug when creating a relay-group with members

### ISSUE THREAD

**Issue by vanstee** [operable/cog#567]
This is the output from creating a relay-group with a single member

```
cogctl relay-groups create default --members=default
ID    f48be4ca-4195-47f5-9c44-d7f597085a83
Name  default

Adding 'default' to relay group 'default': Ok.
Error: nil
```

* Make the output consistent with other commands (list actions "Created default relay-group", "Added default relay to default relay-group" as first output, then print summary)
* Don't render "error: nil"

**Comment by lhaskins** [comment]
# Research/Plans
The `Error: nil` is displayed due to the successful creation of the relay-group. The function returns `nil` instead of `:ok`. We should return `:ok`.

**Comment by mpeck** [comment]
I think we should return :ok when the output is successful. That feels better to me anyway.
