### ISSUE TITLE
`cogctl bootstrap` should really be idempotent

### ISSUE THREAD

**Issue by christophermaier** [operable/cog#574]
Currently, running `cogctl bootstrap` on a previously-bootstrapped system exits with a `1` instead of a `0`. This means the command is not actually idempotent, and forces consumers to deal with a "failure" that isn't really a failure, and still yields a system in the same state as if it hadn't been previously bootstrapped.

**Comment by christophermaier** [comment]
Also, please update the note on http://docs.operable.io/v0.4/docs/bootstrapping-cog when this is fixed. It should reflect the fact that the operation is truly idempotent.

**Comment by tecnobrat** [comment]
One issue I had when bootstrapping with docker is that it does so inside the container.  The container doesn't save state, so the `.cogctl` file is not saved anywhere.

So the next time you run cogctl, you are in a broken state, with no way to get the admin password.  Perhaps this is best off by documenting how a user can create a replacement admin user?  So that they always know the password (because they set it)?

**Comment by christophermaier** [comment]
Hmm, yeah, that's a bit inconvenient 😦 

It looks like there is internal support for specifying an admin password at bootstrap time, but that didn't get exposed in the `cogctl` interface. Should be a straightforward fix.

I think we can do a better job documenting things for this usecase as well. I'll write this up as a new and separate issue to track, since it's distinct from the idempotency bit.

It's excellent feedback, so 💯  for pointing it out @tecnobrat !

**Comment by mpeck** [comment]
I think this is actually a pretty simple fix. The api returns json with an errors key,

`{"errors": {"bootstrap": "Already bootstrapped"}}`

`cogctl` matches on "error" and renders "Already bootstrapped" as an error with an exit code of 1. I think we can just add a special case when we see "Already bootstrapped" returned:

From around line 46 of of `Cogctl.Actions.Bootstrap`
https://github.com/operable/cogctl/blob/2c2113a77427daaab666040c44aa496a32c7032e/lib/cogctl/actions/bootstrap.ex#L46
```
...
      {:error, %{"errors" => %{"bootstrap" => "Already bootstrapped"}}} ->
        display_output("Already bootstrapped")
      {:error, %{"errors" => %{"bootstrap" => error}}} ->
        display_error(error)
      {:error, %{"errors" => error}} ->
...
```
