### ISSUE TITLE
Allow admin password to be specified when calling `cogctl bootstrap`

### ISSUE THREAD

**Issue by christophermaier** [operable/cog#575]
As detailed in https://github.com/operable/cog/issues/574#issuecomment-214406336, if a user bootstraps Cog from inside the cog Docker container, the corresponding `.cogctl` file remains in the container, and doesn't get persisted. If you need to recreate your cog container, you lose the generated admin password, making sad times for everyone.

The bootstrap process already allows for override of the generated password (among other aspects of the admin user), but we don't propagate that out to `cogctl`. 

We should allow users to define their own admin passwords (as well as the other admin user fields) when bootstrapping. Documentation should be updated to reflect this change, as well.

Thanks to @tecnobrat for pointing this out.

**Comment by vanstee** [comment]
The username and password can now be provided when bootstrapping.
