### ISSUE TITLE
Upsert chat handles

### ISSUE THREAD

**Issue by christophermaier** [operable/cog#604]
Currently, it's only really possible for a user to have one active chat handle at a time, governed by the chat adapter that Cog is currently configured to use.

In order to determine whether or not a user is updating or creating a chat handle, one approach is to add a `:show` action to the chat handles controller (currently, the `:index` action is used, which is not ideal).

However, since there can really only be one chat handle active at a time, we can simplify things by merging the current `:create` and `:update` actions into on (effectively) "upsert" operation.

To prevent confusion, we'll require the chat provider name in the API call, and return an error if that name doesn't correspond to the currently-configured chat adapter (until we can relax the "internal ID lookup logic" when chat handles are created).

Also, the database schema currently allows a single Cog user to have multiple chat handles from the same provider. That's not intentional, and can also be fixed in the course of this work.

**Comment by imbriaco** [comment]
:+1:

**Comment by jsteiner** [comment]
👍  Sounds good to me
