### ISSUE TITLE
Doc Cleanup

### ISSUE THREAD

**Issue by kevsmith** [operable/cog#608]
* [ ] Clean up revise all other install documentation with Docker as the default/suggested method
* [ ] Revise all cogctl references to make sure they can easily be run inside a docker container
* [ ] Add "Is Cog right for me?" documentation to help people evaluate Cog before installing
* [ ] Revise "Introducing Cog" section of docs

**Comment by vanstee** [comment]
This is going on with the cog-book rewrite. We can create new issues for anything missing once that's complete.
