### ISSUE TITLE
Ensure embedded commands are compatible with Simplified Calling Convention

### ISSUE THREAD

**Issue by kevsmith** [operable/cog#612]
Depends on #399

**Comment by mpeck** [comment]
This feels like a good opportunity to verify that our usage info is at least roughly formatted the same, and that we have a few tests for each command.

I think the best path is to PR this in batches:
- [ ] batch1 - alias, bundle, echo, filter
- [ ] batch2 - group, help, max, min, permissions
- [ ] batch3 - raw, relay, relay_group, role
- [ ] batch4 - rules, seed, sleep, sort
- [ ] batch5 - sum, table, unique, wc, which

Batch grouping are subject to change depending on the number of changes. I'll update the issue accordingly.
