### ISSUE TITLE
Ensure embedded commands are compatible with ChatOpts Design Guide

### ISSUE THREAD

**Issue by kevsmith** [operable/cog#614]
See [Designing for ChatOps](https://dash.readme.io/project/cog/v0.5.0/docs/designing-for-chatops).

**Comment by vanstee** [comment]
I'm going to run through each command on the following list and create individual issues for each command that needs reworking so we can :+1:/:-1: changes in the researching stage.

* [ ] operable:alias
* [ ] operable:bundle
* [ ] operable:echo
* [ ] operable:filter
* [ ] operable:group
* [ ] operable:help
* [ ] operable:helpers
* [ ] operable:max
* [ ] operable:min
* [ ] operable:permissions
* [ ] operable:raw
* [ ] operable:relay
* [ ] operable:relay-group
* [ ] operable:role
* [ ] operable:rules
* [ ] operable:seed
* [ ] operable:sleep
* [ ] operable:sort
* [ ] operable:sum
* [ ] operable:table
* [ ] operable:unique
* [ ] operable:wc
* [ ] operable:which
* [ ] mist:ec2_create
* [ ] mist:ec2_destroy
* [ ] mist:ec2_find
* [ ] mist:ec2_keypairs
* [ ] mist:ec2_state
* [ ] mist:ec2_tags
* [ ] mist:ec2_vpcs
* [ ] mist:s3_bucket_acl
* [ ] mist:s3_bucket_files
* [ ] mist:s3_buckets

**Comment by vanstee** [comment]
This is mostly done. I think we've covered everything over a few PRs in the past few months.
