### ISSUE TITLE
Add additional arg for stdin to embedded commands

### ISSUE THREAD

**Issue by mpeck** [operable/cog#619]
Currently embedded commands may receive the output from previous commands via `req.cog_env`. This isn't particularly obvious and we also need to use `cog_env` for other, more `env`y things (see #618). To make it more clear embedded commands `handle_message` function will receive an additional argument that contains the decoded json from the previous command. 
```
def handle_message(req, args, stdin) do
...
end
```

parent #399

**Comment by vanstee** [comment]
I was actually wrong about this the command request (passed into `handle_message` as `req`) contains all the env vars that we pass to relay, so I think reading previous output from `req.cog_env` and env vars from `req` is fine for now.
