### ISSUE TITLE
Remove any vestigial mentions of calling convention

### ISSUE THREAD

**Issue by mpeck** [operable/cog#622]
The database still contains a field for 'execution' which I believe refers to the old 'calling_convention' bits. We need to verify that all vestigial mentions of calling convention have been removed from cog.

parent #399

**Comment by vanstee** [comment]
Items to cleanup:

* Remove execution field from command table and model
* Remove once case form Pipeline.Planner
* Remove once/multi docs from commands that mention them
* Fixup tests that callout once/multi
* Remove from documentation
