### ISSUE TITLE
Improve command and bundle help documentation.

### ISSUE THREAD

**Issue by imbriaco** [operable/cog#658]
# Problem

Currently, the amount of documentation related metadata that we store for commands and bundles is limited to an arbitrary text string for each command that is expected to contain the documentation for using the command. This limits the amount of help that we can provide to users and our ability to format that help information in a meaningful way.

Let's remodel of the documentation related parts of bundle configuration and improve the `operable:help` command to provide more useful and consistently structured results

# Proposed Config Changes

All keys are optional unless specifically called out as required.

## Bundles

Add the following keys to the top-level of the bundle configuration:

- **`description`** - Short description of the bundle that can be used by `operable:help` to describe the functions that the bundle provides. (required)
- `long_description` - Longer description that is used when requesting details about the bundle. 
- `author` - String to be included in the AUTHOR section of the bundle help.
- `homepage` - String to be included in the HOMEPAGE section of the bundle help.

## Commands

Add the following optional keys to the configuration of each command:

- `description` - Short description of the command, used when listing the commands in a bundle and in the detailed man page for the command.
- `long_description` - Longer description that is used at the top of the detailed help page for the command.
- `examples` - Examples of use of the command with various options.
- `notes` - Free form NOTES section that will appear at the end of the help page, just above AUTHOR and HOMEPAGE information.
- `arguments` - String to be added to the end of the generated synopsis to represent positional arguments. This is kind of a hack to avoid having to make positional arguments as rigid as Options, so that users can represent things like "instance1 .. instanceN" in their documentation. **I'm not sure if this is the right call for arguments or not. Feedback and ideas are extra requested here.**

# Proposed Help Command Behavior

- `operable:help` - List installed bundles with a short description of each.
- `operable:help <bundle>` - Display long description of a specific bundle and a list of the commands that are included.
- `operable:help <bundle>:<command>` - Display a man page for an individual command.

#### `operable:help`:
```
Available bundles:
  
   * operable - Cog administration and support utilities.
   * mist - Amazon Web Services management tools.

Disabled bundles:

   * format - Support commands for formatting pipeline output.
   * circle - CircleCI integration

To learn more about a specific bundle and the commands available within
it, you can use `operable:help <bundle name>`.
```

#### `operable:help <bundle>`:
```
NAME:
  mist - Amazon Web Services management tools.

DESCRIPTION:
  mist is  collection of commands for managing resources in Amazon
  Web Services. Currently a subset of the EC2, S3, and VPC services
  are included.

  These commands all require a --region option to be included to identify
  the AWS region to operate against. You can select a default region 
  by defining a MIST_DEFAULT_REGION variable in your relay's dynamic
  command configuration.

COMMANDS: 
  * mist:ec2-create - Create an EC2 instance
  * mist:ec2-destroy - Destroy an EC2 instance
  * mist:ec2-find - Find EC2 instances
  * mist:ec2-state - ...
  * mist:ec2-tags - ...
  * mist:keypairs-list - ...
  * mist:s3-bucket-acl - ...
  * mist:s3-bucket-files - ...
  * mist:s3-buckets - ...
  * mist:vpc-list - ...

  For details about a specific command, you can use the  `operable:help <command>`, 
  for example `operable:help mist:ec2-find`.

AUTHOR:
  Kevin Smith <kevin@example.com>

HOMEPAGE: 
  https://github.com/cog-bundles/mist/
```

#### `operable:help <bundle>:<command>`:

Note: The `mist:ec2-find` command doesn't actually have any positional
arguments but I include an `instance_id` argument in the synopsis just
to illustrate how named positional arguments may be handled when 
generating the synopsis.

```
NAME
  mist:ec2-find - Find EC2 instances

DESCRIPTION:
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam molestie augue at diam egestas, 
  ac fringilla orci pulvinar. Pellentesque habitant morbi tristique senectus et netus et malesuada
  fames ac turpis egestas. Nulla id nibh egestas, fermentum magna eu, hendrerit risus. 

SYNOPSIS:
  mist:ec2-find --region=<region> [--state <state>] [--tags <tags>]
                [--ami <ami>] [--return <field_list>] instance_id

REQUIRED OPTIONS:
  --region
      The Amazon Web Services region to find instances in.

OPTIONS:
  --state <state>
      Instance state, e.g. "running", "stopped", etc.
      
  --tags <tag>
      List of tags to find. 

      Tags consist of Key=Value pairs. Multiple tags should be separated
      by commas. 
  --ami <ami>
      EC2 AMI ID to find.

  --return <return>
      A comma separated list of fields to return in the results.

      Available fields: 
        id, pubdns, privdns, state, keyname, ami, kernel, vpc, 
        pubip, privip, az, tags

EXAMPLES:
  Return all instances in the us-east-1 region:
  
    mist:ec2-find --region us-east-1 

  Return instances in the us-east-1 region with the Environment=staging
  tag set:

    mist:ec2-find --region us-east-1 --tags Environment=staging

  Return the instance ID and public IP address for running instances 
  in the us-east-1 region:

    mist:ec2-find --region us-east-1 --state running --return id,pubip

NOTES:
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam molestie augue at diam egestas, 
  ac fringilla orci pulvinar. Pellentesque habitant morbi tristique senectus et netus et malesuada
  fames ac turpis egestas. Nulla id nibh egestas, fermentum magna eu, hendrerit risus.
 
AUTHOR:
  Kevin Smith <kevin@example.com>

HOMEPAGE: 
  https://github.com/cog-bundles/mist/
```

**Comment by vanstee** [comment]
This looks great. The only thing I haven't figured out is how we could do commands that have subcommands with this structure. I think we'd have to add a subcommands section and include options there, otherwise the synopsis is going to look really messy. For instance how should the `relay-groups` command define options and arguments and also list subcommands?

**Comment by imbriaco** [comment]
Thinking out loud re: subcommands, right now they have to (at least from Cog's POV) use the same options as the command they are associated with. We could add `subcommands` array to each `command` object, where each element is just a string name for a subcommand. 

That's not the ultimate solution once we have real subcommands but it might be a start.

Thoughts?

**Comment by vanstee** [comment]
That's close enough to what we're doing already so I think that'll be fine until we have a better way to handle subcommands. It gets weird with require options since they may be manually required when running a specific subcommand, but that's not really something we can fix until we build out subcommand support.

Instead of an array I'll make it a map, so subcommands can have descriptions like we're already doing in the bundle command. https://github.com/operable/cog/blob/master/lib/cog/commands/bundle.ex#L27-L32

**Comment by imbriaco** [comment]
Makes sense! :+1:

**Comment by vanstee** [comment]
Just wanted to note that description was not required in v3 but will be in v4, so it will remain as a nullable field in the db until we drop the v3 schema.

**Comment by vanstee** [comment]
@imbriaco RE: arguments field. This sounds fine to me. I probably wont know if it's right or not until I've hit a weird case while rewriting docs for our bundles.

Another thing that might be nice to allow further customization (flag ordering etc) would be to allow bundle authors to overwrite the entire synopsis field; we'd still generate one from the data available by default though.
