### ISSUE TITLE
Redesign `group` command

### ISSUE THREAD

**Issue by vanstee** [operable/cog#671]
Group was previously built to require long flags for options. Let's convert these flags to subcommands and bias towards args instead of using options. Also we'll restructure the output to be more easily used in a pipeline by always returning either an empty list, a list of groups, or a status message about the change made.

```
USAGE

group <subcommand>

group create <group-name>
group drop <group-name>
group add <group-name> <username>
group remove <group-name> <username>
group list

EXAMPLES

group create ops
> Created group ops

group drop ops
> Dropped group ops

group add ops vanstee
> Added user vanstee to group ops

group remove ops vanstee
> Removed user vanstee from group ops

group list
> NAME  USERS
  ops   vanstee imbriaco kevsmith chris mpeck
  ux    shelton
```

**Comment by christophermaier** [comment]
Looks sooooooo much nicer 👍

**Comment by imbriaco** [comment]
There are two different usage patterns that we're trying to collapse into this command. Managing existence of a group (create, delete) and managing the details of that group (show, add/remove users). 

I wonder if there might be a better model by thinking about this a little differently. Would love thoughts on the following possible UI:

**Group Existence:**
```
group list
group create <group-name>
group delete <group-name>
```

**Individual Group Management:**
```
group <group-name> add <user1> .. <userN> 
group <group-name> remove <user> .. <userN>
```

**Comment by kevsmith** [comment]
I like @imbriaco's syntax ideas. I wonder if regularizing the syntax makes it easier to implement and document?

```
group list
group <group-name> create
group <group-name> delete
group <group-name> add <user1> .. <userN>
group <group-name> remove <user1> .. <userN>
```

**Comment by imbriaco** [comment]
After discussing in the office, @kevsmith and I are both liking: 

```
group members <group-name> add <user1> .. <userN>
group members <group-name> remove <user1> .. <userN>
```

It keeps the `command subcommand target` flow, though admittedly there's a second subcommand tacked on after the target. I really like the way it reads though.

**Comment by christophermaier** [comment]
A benefit of the `group members <group-name> etc.` syntax is that you don't have to carve out exceptions for group names. That is, if the scheme was like

```
group list
group create <group-name>
group delete <group-name>
group <group-name> add <user1> .. <userN> 
group <group-name> remove <user> .. <userN>
```

you might run into issues if someone created groups named `list`, `create`, or `delete`. Granted, this is probably not likely to happen in real life, but it'd be a pain for anyone that happened to hit it.

**Comment by vanstee** [comment]
I really like the addition of `<user1> .. <userN>`, not sure how I missed that before. The only change I would make is to change the order of the group name back to this:

```
group list
group create <group-name>
group delete <group-name>
group add <group-name> [users...]
group remove <group-name> [users...]
```

There are two reasons for the change: the problem with "groups sharing names with subcommands" that @christophermaier mentioned above and that if we ever want to move to a special subcommand syntax where `group-create` and `group-add` turn into `group create` and `group add` the ordering of the `<group-name>` arg might make that more complex than it needs to be. Also just looking at a few popular cli tools that seem well designed, they seem to follow this ordering; `command <subcommands...> [args in order of importance]`. Here's `git remote` for instance:

```
       git remote [-v | --verbose]
       git remote add [-t <branch>] [-m <master>] [-f] [--[no-]tags] [--mirror=<fetch|push>] <name> <url>
       git remote rename <old> <new>
       git remote remove <name>
       git remote set-head <name> (-a | --auto | -d | --delete | <branch>)
       git remote set-branches [--add] <name> <branch>...
       git remote get-url [--push] [--all] <name>
       git remote set-url [--push] <name> <newurl> [<oldurl>]
       git remote set-url --add [--push] <name> <newurl>
       git remote set-url --delete [--push] <name> <url>
       git remote [-v | --verbose] show [-n] <name>...
       git remote prune [-n | --dry-run] <name>...
       git remote [-v | --verbose] update [-p | --prune] [(<group> | <remote>)...]
```

The best example is `git remote set-url <name> <newurl>`.

**Comment by imbriaco** [comment]
@vanstee Did you see the `group members` example above, e.g:

```
group members <group-name> add <user1> .. <userN>
group members <group-name> remove <user1> .. <userN>
```

I think that gets you the best of both worlds without the confusion between `group create` and `group add` that I have with the initial proposal.

**Comment by vanstee** [comment]
Ah missed the members bit, still more of a fan of the `group members add <group-name> <users...>` style for the reasons above but would be happy to implement that. This affects a lot of other commands as well if we want to be consistent.

**Comment by imbriaco** [comment]
I'm :+1: with `group members add <group-name> <users...>` and similar for `remove`.
