### ISSUE TITLE
Redesign `sum` command

### ISSUE THREAD

**Issue by vanstee** [operable/cog#679]
Sum currently operates on a list of args when it should instead sum up a list of values from the input list.

```
USAGE

sum <$variable>

EXAMPLES

seed '[{"a": 2}, {"a": 1}, {"a": 3}]' | sum $a
> 6

seed '[{"a": {"b": 2}}, {"a": {"b": 1}}, {"a": {"b": 3}}]' | min $a.b
> 6
```

**Comment by christophermaier** [comment]
Closing; there is no more `sum` command. It should be in a separate bundle, if desired.
