### ISSUE TITLE
Ideas for useful chat commands

### ISSUE THREAD

**Issue by vanstee** [operable/cog#682]
- [ ] count - counts items in the input list
- [ ] pluck - select specific keys from each input
- [ ] head - grab first n items off beginning of input list
- [ ] tail - grab frist n items off end of input list
- [ ] jq - queries json (see https://stedolan.github.io/jq/manual/)
- [ ] format - a fancier echo with interpolation `format "first:%s second:%s" $first $second`

**Comment by christophermaier** [comment]
Closing; we've got a bunch of these now.
