### ISSUE TITLE
Bundle: Pingdom

### ISSUE THREAD

**Issue by imbriaco** [operable/cog#699]
* pingdom:check list
* pingdom:check show <check_id>
* pingdom:check results [-c|--count <count>] <check_id>
  * Default for count is 1 to show most recent check result data.

see-also: #698

**Comment by christophermaier** [comment]
@imbriaco Just to clarify:

* `pingdom:check list` corresponds to https://www.pingdom.com/resources/api#MethodGet+Check+List
* `pingdom:check show` corresponds to https://www.pingdom.com/resources/api#MethodGet+Detailed+Check+Information (and so should probably be `pingdom:check show $ID`, correct?)
* `pingdom:check results $ID --count=X` corresponds to https://www.pingdom.com/resources/api#MethodGet+Raw+Check+Results

**Comment by imbriaco** [comment]
Yep, you got it.

**Comment by christophermaier** [comment]
https://github.com/cogcmd/pingdom
