### ISSUE TITLE
Bundle: Twitter

### ISSUE THREAD

**Issue by imbriaco** [operable/cog#702]
* `twitter:tweet <message>`
* `twitter:tweet [-a|--as <user>] <message>`

**Config:**

There should be a set of configuration values that are used for tweets that are sent with no `-a` or `--as` option set.

```
TWITTER_API_KEY=<api_key>
TWITTER_CONSUMER_TOKEN=<token>
TWITTER_ACCESS_KEY=<access_key>
```

For each additional user, there should be a parallel set of variables with the username appended:

```
TWITTER_API_KEY_<user>=<api_key>
TWITTER_CONSUMER_TOKEN_<user>=<token>
TWITTER_ACCESS_KEY_<user>=<access_key>
```

Bonus points for a default user per-room: 

```
TWITTER_USER_<room>=<user>
```

see-also: #698

**Comment by christophermaier** [comment]
There are a few considerations for making this (and future commands) "room aware". First and foremost, Relay needs to propagate room information into the command's execution environment. This is pretty straightforward and shouldn't be much of an issue once we determine what specific data we want to expose.

The more interesting wrinkle is that, for the most part, what a "room" is in the system is pretty opaque outside of the chat adapters. Generally, it's a map with `id` and `name` keys (this is the case for normal Slack, HipChat, and IRC channels), but some cases differ (notably one-on-one Slack chat channels, which only have an ID). It seems like a "name" is all that a Cog command would really care about at the moment; anything adapter-specific seems like a good way to tightly couple commands to adapters (in other words, "bad"). If that's the case, then we'd want to have some kind of contract stating that "a 'room' is a map with at least a 'name' key". We could informally do that now, seeing as how "adapter" is still a bit of a loose contract itself, and just not include a value for `COG_ROOM` (what I presume the environment variable for this would eventually be named) in cases like the one-on-one Slack chat. Commands that want to be room-aware would just need to cope with an undefined value.

**Comment by imbriaco** [comment]
That makes sense. I think a string with the room name is the right level of abstraction and deciding how to handle empty values should be left up to the commands in much the same way that missing positional arguments are.

**Comment by christophermaier** [comment]
We're going to hold off on room-awareness right now, as the proposed mechanism would make it possible to circumvent authorization rules that restrict on the basis of the `--as` option (just tweet from a room that uses that restricted account as the default). We're going to think up a way to incorporate some notion of location into the authorization rules in order to handle this in a more principled, consistent, and intelligible manner.

**Comment by christophermaier** [comment]
Closing: https://github.com/cog-bundles/twitter
