### ISSUE TITLE
Bundle: Jenkins

### ISSUE THREAD

**Issue by tecnobrat** [operable/cog#703]
Would love to see a bundle that you can access things from jenkins.

From running jobs with parameters to seeing the status of running or finished jobs.

**Comment by jesselang** [comment]
Thanks for your interest in the Cog project!

We're currently focusing on core features of the framework, so we're not able to work on this bundle at this time. However, we would love to see this taken up by someone who has an itch to scratch, and we're happy to support those efforts by answering any questions that might come up in the process.

For more information about writing command bundles for Cog, be sure to check out: https://cog-book.operable.io/sections/writing_a_command_bundle.html
