### ISSUE TITLE
minor typo in my_bundle.yaml

### ISSUE THREAD

**Issue by bortels** [operable/cog#718]
The my_bundle.yaml file at http://docs.operable.io/docs/installing-your-first-command-bundle has an extra space on the first line that will prevent it from functioning. Could be confusing to someone who is not familar with yaml syntax (it took me a minute to notice it).

**Comment by Shelton** [comment]
Done and done, thanks @bortels for pointing it out + @kevsmith for the, "look here `- --` = `---`"
