### ISSUE TITLE
Automatically create new users on first invocation

### ISSUE THREAD

**Issue by imbriaco** [operable/cog#72]
Cog should allow admins to configure it to create a new user the first time someone speaks to it either via a direct message or a command invocation attempt. This needs to be scoped further, but conceptually I'm thinking of configuration that might look like this:

```
config :cog, Cog.Models.User,
  auto_create: true, # Should Cog automatically create new users? Default false.
  auto_group: "cog:users" # Initial group for automatically created users. Default nil.
```

**Comment by kevsmith** [comment]
Shipped in [Cog 0.10](https://github.com/operable/cog/releases/tag/0.10.0)
