### ISSUE TITLE
default user

### ISSUE THREAD

**Issue by bortels** [operable/cog#727]
This is probably an enhancement request.
I run an infobot where the vast majority of the users are read-only, and the fact that they have access to slack is sufficient to allow them to run commands that do lookups and answer various questions. Adding hundreds of users to the database, and keeping up with additions, would be a nightmare.
It would be nice if a user that was not in the database is given a default group (maybe named "default") that could be assigned roles and permissions as per usual.

**Comment by vanstee** [comment]
Closing in favor of #728. Thanks @bortels
