### ISSUE TITLE
Make carrier credential storage backend pluggable

### ISSUE THREAD

**Issue by imbriaco** [operable/cog#76]
The `Carrier.CredentialStore` in operable/carrier currently stores message signature related credentials to a local DETS database. This storage interface needs to be abstracted so that operable/cog can store credentials in the database while retaining the DETS option for operable/relay.

This would remove the only piece of local state that has to be persisted with cog and simplify hosting options.

**Comment by kevsmith** [comment]
Closing since Carrier creds and auth have been removed.
