### ISSUE TITLE
Revise how we protect cog-admin group membership

### ISSUE THREAD

**Issue by christophermaier** [operable/cog#796]
Previously we implemented a guard based on the name of the admin user we create at bootstrap; basically, this user can never be removed from the `cog-admin` group.
(see https://github.com/operable/cog/blob/master/priv/repo/migrations/20160419154716_protect_admin_role_permissions.exs)

However, since users can override the default name of this first user at bootstrap time, this may not always work.

Instead, we should engineer the guards such that the last user in the `cog-admin` group cannot be deleted, regardless of their name. There should always be at least one user in this group.

A corollary is that you cannot delete a user if it is the last member of the `cog-admin` group.

**Comment by christophermaier** [comment]
There may be implications from https://github.com/operable/cog/issues/794 as well.

**Comment by kevsmith** [comment]
Summary of in-office conversation:

There are essentially two general approaches to implement protected object deletion.

### 1. Push invariant enforcement to the DB by converting `cascade` relations to `restrict`.

#### Pros
- Consistent and reliable enforcement
- Minimal implementation effort
- Easy to implement for data types with shallow relation graphs

#### Cons
- Forcibly deleting objects requires manual implementation of cascading deletes to the related
- Manual cascades could be tricky/tedious to implement for data types with deep/wide relation graphs or cases where the deletion invariant is conditionally applied (e.g. "if bundle format version > 4 then enforce deletion invariant") 

### 2. Implement deletion invariant checks in application code only.

#### Pros
- No schema changes required
- Implementing invariant checks is relatively straightforward
- Supports blanket and conditional invariant enforcement

#### Cons
- Only protects deletions which flow thru application code
- Incurs additional query overhead to check invariants before issuing delete
- Requires strict adherence to the repository pattern to ensure uniform invariant enforcement

We've decided to mull this over further and punt implementation to a future Cog release.

**Comment by vanstee** [comment]
Added an issue to include `--force` flags for command affected by this change in cogctl. https://github.com/operable/cog/issues/1328

**Comment by vanstee** [comment]
Implemented in https://github.com/operable/cog/pull/1322
