### ISSUE TITLE
Ensure our launch bundles have description strings for the bundle and all commands

### ISSUE THREAD

**Issue by christophermaier** [operable/cog#819]
- [x] [circle](https://github.com/cogcmd/circle): (https://github.com/cogcmd/circle/pull/1)
- [x] [format](https://github.com/cogcmd/format): (https://github.com/cogcmd/format/pull/5)
- [x] [mist](https://github.com/cogcmd/mist)
- [x] [net](https://github.com/cogcmd/net): (https://github.com/cogcmd/net/pull/2)
- [x] [pagerduty](https://github.com/cogcmd/pagerduty): (https://github.com/cogcmd/pagerduty/pull/1)
- [x] [pingdom](https://github.com/cogcmd/pingdom): (https://github.com/cogcmd/pingdom/pull/2)
- [x] [pipewrench](https://github.com/cogcmd/pipewrench): (https://github.com/cogcmd/pipewrench/pull/2)
- [x] [statuspage](https://github.com/cogcmd/statuspage): (https://github.com/cogcmd/statuspage/pull/1)
- [x] [twitter](https://github.com/cogcmd/twitter): (https://github.com/cogcmd/twitter/pull/1)

**Comment by christophermaier** [comment]
I'll take `pipewrench` and `format`

**Comment by mpeck** [comment]
I'll do statuspage

**Comment by mpeck** [comment]
I think the descriptions for mist look fine. Do you guys see any issues with them? @christophermaier @vanstee

**Comment by vanstee** [comment]
@mpeck Could you just fix the "Finds an ec2 instances" one real quick? Other than that, they're fine.

**Comment by christophermaier** [comment]
I'll take `circle`

**Comment by christophermaier** [comment]
I'll also tweak the `mist` description.

**Comment by christophermaier** [comment]
Never mind, looks like @mpeck got that already.

**Comment by christophermaier** [comment]
All done!
