### ISSUE TITLE
Update "revoke role from group" API

### ISSUE THREAD

**Issue by christophermaier** [operable/cog#825]
With the restriction that the `cog-admin` role cannot be revoked from the `cog-admin` group, the contract for role revocation changes from something that can always occur, to something that can now fail. The API needs to be updated to reflect this, and corresponding updates to cog-api-client, cogctl, and flywheel need to occur.

**Comment by mpeck** [comment]
To start we need to move the grant and revoke handling bits from the controller to the repository. This should match up with the pattern we are using for other interactions with models and also help reduce some of the code duplication. Then we can handle error messages in the repository which should help standardize the output a bit.

Cog
- [ ] rework role_grant_controller to leverage the repository
- [ ] return an error to the user when a revoke is invalid

cog-api
- [ ]  handle the new error returned when a revoke is invalid

cogctl
- [ ] update cog-api dep
- [ ] verify that tests are passing
- [ ] verify that the correct error is presented to the user

flywheel
- [ ] update cog-api dep
- [ ] verify that tests are passing
- [ ] verify that the proper errors are shown to users
