### ISSUE TITLE
Break out embedded bundle to separate OTP application

### ISSUE THREAD

**Issue by kevsmith** [operable/cog#846]
We need to extract the embedded command bundle into a separate OTP app which is versioned separately from Cog to allow for rolling back to previous versions. The current state is such that Cog and the embedded bundle share the same version number. This means the embedded bundle will block all attempts to roll back since it can't do downgrades.

Separating the version numbers allows the embedded bundle to only block roll backs which are truly problematic (ie, when the contents of the embedded bundle changes).

**Comment by christophermaier** [comment]
We're not breaking out the bundle to a separate app, since the implementation is closely coupled to Cog's internals. #858 was a step toward unlinking them, which should be good enough for right now.
