### ISSUE TITLE
password reset endpoints

### ISSUE THREAD

**Issue by mpeck** [operable/cog#894]
We need an endpoint to reset passwords. There should be two endpoints. The first should accept an email. If the email corresponds to a user then Cog will generate a token and create a url based on a configured url with the token as a query param. It should then send an email containing the generated url and a message to the email address. The second endpoint will accept the token and a new password.

`POST /reset-password`
```
{ "email_address": "bob@example.com" }
```

`PUT /reset-password/<token>`
```
{ "password": "5ecrit" }
```

Depends on https://github.com/operable/cog/issues/895

**Comment by vanstee** [comment]
@mpeck Seems fine. Wonder if we need to whitelist the urls allowed here. Wouldn't want to send an email with a link to "evilsite.com" that contains a password reset token.

**Comment by mpeck** [comment]
That's a good point @vanstee. Maybe the url should be config in Cog?

**Comment by vanstee** [comment]
Yeah that's probably better :+1:

**Comment by mpeck** [comment]
Now that I think about it. I'm just gonna drop the message bit too. That can just be in the email template on Cog. We can tweak it later if need be.
