### ISSUE TITLE
Beef up cogctl docs

### ISSUE THREAD

**Issue by kevsmith** [operable/cog#930]
- How to get and install `cogctl` on a separate machine
- Configuring `cogctl`
- Troubleshooting common problems

**Comment by ChristopherBiscardi** [comment]
Having an example that uses a minimal container (think `alpine`+`cogctl`) from "somewhere else" would be nice. For me "somewhere else" would be somewhere on the same overlay network, but it could also be a remote host.

```sh
docker run -ite COG_HOST=cog cog/cogctl sh
> cogctl groups add cog-admin --email="patrick@operable.io"
```

**Comment by kevsmith** [comment]
Tagging this with docs and pushing to 0.15.
