### ISSUE TITLE
Update Docker installation documentation

### ISSUE THREAD

**Issue by christophermaier** [operable/cog#932]
The Docker installation documentation is outdated (refers to 0.10.0, doesn't mention `docker-compose-override.yml` or how to use that, etc.)

**Installation**
- [x] Update Docker installation copy reference to 0.13.0
- [x] Update Docker link to 0.13.0

**Cog with Docker** (http://docs.operable.io/docs/cog-with-docker-compose)
- [x] Update to match Installation page + consider making this an installation process from the installation. (Deleted page)

Time to update!

Related: #905

**Comment by Shelton** [comment]
Updated Docs so that there were more distinct sections. Will ask the community soon about their thoughts on our current installation.

**Comment by Shelton** [comment]
* @kevsmith will update the docs to reflect the correct references to the `docker-compose.yaml`
* hid the page that referenced Cog with docker-compose
