### ISSUE TITLE
Newlines following `each` / `join` tags get inappropriately swallowed

### ISSUE THREAD

**Issue by christophermaier** [operable/cog#945]
The template snippet

```
...
**Groups**: ~join var=$results[0].groups as=g~~$g.name~~end~
**Handles**: ~join var=$results[0].chat_handles as=h~~$h.handle~ (~$h.chat_provider.name~)~end~
...
```

ends up getting rendered to the following directives:

```
...
%{"name" => "bold", "text" => "Groups"},
%{"name" => "text", "text" => ": dev, ops**Handles**: the_cog (Slack)"}
...
```

Internally, the `DirectivesGenerator` is receiving the following:

```
...
%{name: :bold, text: "Groups"},
%{name: :text, text: ": dev, ops"},
%{name: :text, text: "*"},
%{name: :text, text: "*Handles"},
%{name: :text, text: "*"},
%{name: :text, text: "*: the"},
%{name: :text, text: "_cog (Slack)"},
%{name: :newline}
...
```

Somehow, the trailing newline following the `join` tag end is being removed, and the bold formatting is being joined to the `join` tag's output. This behavior was introduced in https://github.com/operable/greenbar/commit/c31976c00a3df361843368ed70b8b1518f7b03f2, but a fix isn't immediately apparent.

(This was observed with `join` and `each` tags, even though the above example only deals with `join`; both tags have an almost identical implementation, though).

**Comment by christophermaier** [comment]
Current workaround is to manually add a newline in the template, like so:

```
...
**Groups**: ~join var=$results[0].groups as=g~~$g.name~~end~

**Handles**: ~join var=$results[0].chat_handles as=h~~$h.handle~ (~$h.chat_provider.name~)~end~
...
```

**Comment by kevsmith** [comment]
I believe this is fixed with the addition of paragraph support to `greenbar`. Closing.
