### ISSUE TITLE
Include config section in bundle docs for env vars

### ISSUE THREAD

**Issue by vanstee** [operable/cog#948]
Man pages generally have a config section for env vars or general configuration. Since our bundles have similar needs, let's include a section like that for bundles when there's a clear need.

**Comment by kevsmith** [comment]
Can we do this without requiring another bundle config version bump? If so, I'm all for it. If not, let's discuss.

**Comment by vanstee** [comment]
Yup. Since it's optional, I think we'll be ok just including it without a version bump.
