### ISSUE TITLE
Audit channel for cog configuration

### ISSUE THREAD

**Issue by ktheory** [operable/cog#957]
As a Cog configuration evolves, it can be difficult to keep track of who changed what when. To audit Cog configuration changes, it'd be helpful to specify a chat room as a Cog audit channel.

Once configured, it'd log a message anytime someone changed Cog resources like:
- roles
- groups
- permissions
- users
- bundles
- relays
- relay-groups

Cog admins could consult the channel to clarify user privileges are being maintained appropriately, and debug issues when relays and bundles don't work as expected.

Some sample messages:

```
Alice added Bob to the Deployers group.

Bob enabled bundle "format" version 0.4.2.

Carol created the "production-vpc" relay group.
```

**Comment by vanstee** [comment]
This is an excellent idea :+1:

Might be nice to have a channel for error messages from Cog and Relay.
