### ISSUE TITLE
Feature: LDAP integration

### ISSUE THREAD

**Issue by kevsmith** [operable/cog#965]
Specifically for Cog user accounts and user authentication

**Comment by imbriaco** [comment]
In the interests of full transparency, I want to make sure we're clear that while we want to support external authentication integration with LDAP, we don't know whether this will be part of open source Cog or whether it will be a paid feature. We'll try to be as open as possible as we go down the path toward building this out and as we progress in that decision process.

In general, the way we think about these things is any feature that we expect *everyone* to use will be part of the open source Cog project. You should be able to get up and running with Cog and have complete access to its feature set without paying us anything.

On the other hand, If there are specific features that we believe are primarily applicable to larger companies or that are specific to narrower use cases, we may consider them as part of a paid option. If we do that, those features will be decoupled from the core of Cog in such a way that we only use interfaces that are also available to open source users. We will never use private interfaces as a barrier to keep the open source Cog from competing with any commercial offerings that we build.

**Comment by agis-** [comment]
@imbriaco Thanks for being clear. This will be on our radar.

**Comment by christophermaier** [comment]
Closing due to age; re-open as the needed.
