### ISSUE TITLE
First-class subcommands

### ISSUE THREAD

**Issue by vanstee** [operable/cog#970]
For a while we've been implementing subcommands manually by parsing args in normal commands. This approach is not so great due to problems related to how options, rules, and help docs work. So to fix it we need to add first class support of subcommands into Cog.

What we need at a minimum:
- Subcommands need to be defined in the bundle config as individual commands (with options and rules)
- Subcommands should have their own help docs, separate from the base command
- Ideally invocations would know how to parse subcommands and could fail while parsing if a subcommand doesn't exist

A couple of ideas to think about when implementing this:
- It'd be nice if subcommands followed the implementation of git subcommands like `git-commit` (normal commands with the base command and subcommand separated by a dash).
- We will most likely need a way to define default subcommands to run, but we need to figure out how that'll work if a base command exists.

**Comment by kevsmith** [comment]
What problem(s) do subcommands solve?

**Comment by imbriaco** [comment]
To me they're primarily syntactic sugar for grouping related commands logically for UX purposes. Let's take a couple of commands from the work in progress AWS CloudFormation bundle as an example:

```
cfn:template-list
cfn:template-show
```

Today, those are fully separate commands from the point of view of Cog, which I think is probably appropriate and sidesteps many issues around the rule language and so on. The only obvious downside that I see is that it's a little bit clunky to type them with the hyphen. 

Off the top of my head, if the subcommands were parser sugar that allowed `template list` to be transformed to `template-list` if there was a matching command and no conflicting `template` command, that might be sufficient.

**Comment by vanstee** [comment]
For larger bundles, subcommands are used as a way to group commands and ideally reduce noise when asking for help output, but also make longer commands more readable. For instance, imagine a github command that has commands related to both repos and organizations. They both have list, info, create, update, and delete actions. Currently you'd create command names like, repo-list, repo-info, repo-create, etc, and org-list, org-info, etc, which is ugly but would work just fine. But, if you wanted to to list all the actions that you can do to a repo, there's not a great way to do that other than filtering out the list of commands. Now imagine You have a sub-resource, like a repo's committers, which also has list, info, add, and remove actions. Without subcommands you'd end up with long command names like repo-committer-list and can't easily ask for help related to the actions at a particular level of command.

We can get away with dasherized commands for a while and especially in smaller bundles. It's mostly an issue in bundles where there are a huge number of commands and it's also just annoying to type.

**Comment by vanstee** [comment]
@kevsmith Guessing this is done already with our git style subcommand support?

**Comment by kevsmith** [comment]
git style subcommand parsing addresses most, if not all, of the same user cases. Closing.
