### ISSUE TITLE
Version bundles not commands

### ISSUE THREAD

**Issue by kevsmith** [operable/cog#98]
I just noticed Cog versions commands instead of bundles. This strikes me as unnecessarily complicated since bundled commands all live within the same bundle directory structure.  Versioning bundles makes more sense to me and seems as thought it'd be easier to implement.

**Comment by vanstee** [comment]
Just to update this issue, we no longer version commands. But versioning bundles is still something we need to implement.

**Comment by vanstee** [comment]
Also worth noting that the bundle config now includes a version number. But, we'll still need to make sure that only one version of each bundle is enabled at a time and that you can enable/disable bundle versions via cogctl.

**Comment by vanstee** [comment]
For now we'll just persist the value form the bundle config and revisit the cogctl stuff in a later issue.
