### ISSUE TITLE
Support with tag in templates

### ISSUE THREAD

**Issue by vanstee** [operable/cog#996]
it's common to want to conditionally change scope, similar to how mustache templates work. Let's implement a with tag to do exactly that. Here's an example:

```
~with $command.bundle.author as=bundle_author~
  Author: ~$bundle_author~
~end~
```

which is essentially the same as:

```
~if cond=$command.bundle.author~
  Author: $command.bundle.author~
~end~
```

**Comment by christophermaier** [comment]
This issue was moved to operable/greenbar#53
